;; Auto-generated pinout — DO NOT EDIT
;; Source of truth for pin ID → function name mapping
(pinout "TXS0108EZXYR"
  (pin A1 "VCCA")
  (pin A2 "A2")
  (pin A3 "A4")
  (pin A4 "A6")
  (pin A5 "A8")
  (pin B1 "A1")
  (pin B2 "A3")
  (pin B3 "A5")
  (pin B4 "A7")
  (pin B5 "OE")
  (pin C1 "B1")
  (pin C2 "B3")
  (pin C3 "B5")
  (pin C4 "B7")
  (pin C5 "GND")
  (pin D1 "VCCB")
  (pin D2 "B2")
  (pin D3 "B4")
  (pin D4 "B6")
  (pin D5 "B8")
)
