//
// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright (C) 2026 KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <http://www.gnu.org/licenses/>.

//
// wizards.proto
// Messages that describe content generation wizards

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: common/types/wizards.proto

package wizards

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	anypb "google.golang.org/protobuf/types/known/anypb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type WizardParameterDataType int32

const (
	WizardParameterDataType_WPDT_UNKNOWN  WizardParameterDataType = 0
	WizardParameterDataType_WPDT_DISTANCE WizardParameterDataType = 1 // int32 nanometers
	WizardParameterDataType_WPDT_AREA     WizardParameterDataType = 2 // int32 square nanometers
	WizardParameterDataType_WPDT_VOLUME   WizardParameterDataType = 3 // int32 cubic nanometers (not currently supported in KiCad)
	WizardParameterDataType_WPDT_TIME     WizardParameterDataType = 4 // int32 picoseconds
	WizardParameterDataType_WPDT_ANGLE    WizardParameterDataType = 5 // double degrees
	WizardParameterDataType_WPDT_STRING   WizardParameterDataType = 6
	WizardParameterDataType_WPDT_INTEGER  WizardParameterDataType = 7 // int32 (quantity, etc)
	WizardParameterDataType_WPDT_REAL     WizardParameterDataType = 8 // double value
	WizardParameterDataType_WPDT_BOOL     WizardParameterDataType = 9 // boolean flag
)

// Enum value maps for WizardParameterDataType.
var (
	WizardParameterDataType_name = map[int32]string{
		0: "WPDT_UNKNOWN",
		1: "WPDT_DISTANCE",
		2: "WPDT_AREA",
		3: "WPDT_VOLUME",
		4: "WPDT_TIME",
		5: "WPDT_ANGLE",
		6: "WPDT_STRING",
		7: "WPDT_INTEGER",
		8: "WPDT_REAL",
		9: "WPDT_BOOL",
	}
	WizardParameterDataType_value = map[string]int32{
		"WPDT_UNKNOWN":  0,
		"WPDT_DISTANCE": 1,
		"WPDT_AREA":     2,
		"WPDT_VOLUME":   3,
		"WPDT_TIME":     4,
		"WPDT_ANGLE":    5,
		"WPDT_STRING":   6,
		"WPDT_INTEGER":  7,
		"WPDT_REAL":     8,
		"WPDT_BOOL":     9,
	}
)

func (x WizardParameterDataType) Enum() *WizardParameterDataType {
	p := new(WizardParameterDataType)
	*p = x
	return p
}

func (x WizardParameterDataType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WizardParameterDataType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_wizards_proto_enumTypes[0].Descriptor()
}

func (WizardParameterDataType) Type() protoreflect.EnumType {
	return &file_common_types_wizards_proto_enumTypes[0]
}

func (x WizardParameterDataType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WizardParameterDataType.Descriptor instead.
func (WizardParameterDataType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{0}
}

type WizardParameterCategory int32

const (
	WizardParameterCategory_WPC_UNKNOWN  WizardParameterCategory = 0
	WizardParameterCategory_WPC_PACKAGE  WizardParameterCategory = 1
	WizardParameterCategory_WPC_PADS     WizardParameterCategory = 2
	WizardParameterCategory_WPC_3DMODEL  WizardParameterCategory = 3
	WizardParameterCategory_WPC_METADATA WizardParameterCategory = 4
	WizardParameterCategory_WPC_RULES    WizardParameterCategory = 5
)

// Enum value maps for WizardParameterCategory.
var (
	WizardParameterCategory_name = map[int32]string{
		0: "WPC_UNKNOWN",
		1: "WPC_PACKAGE",
		2: "WPC_PADS",
		3: "WPC_3DMODEL",
		4: "WPC_METADATA",
		5: "WPC_RULES",
	}
	WizardParameterCategory_value = map[string]int32{
		"WPC_UNKNOWN":  0,
		"WPC_PACKAGE":  1,
		"WPC_PADS":     2,
		"WPC_3DMODEL":  3,
		"WPC_METADATA": 4,
		"WPC_RULES":    5,
	}
)

func (x WizardParameterCategory) Enum() *WizardParameterCategory {
	p := new(WizardParameterCategory)
	*p = x
	return p
}

func (x WizardParameterCategory) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WizardParameterCategory) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_wizards_proto_enumTypes[1].Descriptor()
}

func (WizardParameterCategory) Type() protoreflect.EnumType {
	return &file_common_types_wizards_proto_enumTypes[1]
}

func (x WizardParameterCategory) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WizardParameterCategory.Descriptor instead.
func (WizardParameterCategory) EnumDescriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{1}
}

type WizardContentType int32

const (
	WizardContentType_WCT_UNKNOWN   WizardContentType = 0
	WizardContentType_WCT_SYMBOL    WizardContentType = 1
	WizardContentType_WCT_FOOTPRINT WizardContentType = 2
)

// Enum value maps for WizardContentType.
var (
	WizardContentType_name = map[int32]string{
		0: "WCT_UNKNOWN",
		1: "WCT_SYMBOL",
		2: "WCT_FOOTPRINT",
	}
	WizardContentType_value = map[string]int32{
		"WCT_UNKNOWN":   0,
		"WCT_SYMBOL":    1,
		"WCT_FOOTPRINT": 2,
	}
)

func (x WizardContentType) Enum() *WizardContentType {
	p := new(WizardContentType)
	*p = x
	return p
}

func (x WizardContentType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WizardContentType) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_wizards_proto_enumTypes[2].Descriptor()
}

func (WizardContentType) Type() protoreflect.EnumType {
	return &file_common_types_wizards_proto_enumTypes[2]
}

func (x WizardContentType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WizardContentType.Descriptor instead.
func (WizardContentType) EnumDescriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{2}
}

type WizardGenerationStatus int32

const (
	WizardGenerationStatus_WGS_UNKNOWN WizardGenerationStatus = 0
	WizardGenerationStatus_WGS_OK      WizardGenerationStatus = 1
	WizardGenerationStatus_WGS_ERROR   WizardGenerationStatus = 2
)

// Enum value maps for WizardGenerationStatus.
var (
	WizardGenerationStatus_name = map[int32]string{
		0: "WGS_UNKNOWN",
		1: "WGS_OK",
		2: "WGS_ERROR",
	}
	WizardGenerationStatus_value = map[string]int32{
		"WGS_UNKNOWN": 0,
		"WGS_OK":      1,
		"WGS_ERROR":   2,
	}
)

func (x WizardGenerationStatus) Enum() *WizardGenerationStatus {
	p := new(WizardGenerationStatus)
	*p = x
	return p
}

func (x WizardGenerationStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WizardGenerationStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_wizards_proto_enumTypes[3].Descriptor()
}

func (WizardGenerationStatus) Type() protoreflect.EnumType {
	return &file_common_types_wizards_proto_enumTypes[3]
}

func (x WizardGenerationStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WizardGenerationStatus.Descriptor instead.
func (WizardGenerationStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{3}
}

type WizardIntParameter struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Value   int32                  `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Default int32                  `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	Min     *int32                 `protobuf:"varint,3,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max     *int32                 `protobuf:"varint,4,opt,name=max,proto3,oneof" json:"max,omitempty"`
	// If present, will require the value to be a multiple of this number
	Multiple      *int32 `protobuf:"varint,5,opt,name=multiple,proto3,oneof" json:"multiple,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardIntParameter) Reset() {
	*x = WizardIntParameter{}
	mi := &file_common_types_wizards_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardIntParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardIntParameter) ProtoMessage() {}

func (x *WizardIntParameter) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardIntParameter.ProtoReflect.Descriptor instead.
func (*WizardIntParameter) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{0}
}

func (x *WizardIntParameter) GetValue() int32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *WizardIntParameter) GetDefault() int32 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *WizardIntParameter) GetMin() int32 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *WizardIntParameter) GetMax() int32 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

func (x *WizardIntParameter) GetMultiple() int32 {
	if x != nil && x.Multiple != nil {
		return *x.Multiple
	}
	return 0
}

type WizardRealParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         float64                `protobuf:"fixed64,1,opt,name=value,proto3" json:"value,omitempty"`
	Default       float64                `protobuf:"fixed64,2,opt,name=default,proto3" json:"default,omitempty"`
	Min           *float64               `protobuf:"fixed64,3,opt,name=min,proto3,oneof" json:"min,omitempty"`
	Max           *float64               `protobuf:"fixed64,4,opt,name=max,proto3,oneof" json:"max,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardRealParameter) Reset() {
	*x = WizardRealParameter{}
	mi := &file_common_types_wizards_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardRealParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardRealParameter) ProtoMessage() {}

func (x *WizardRealParameter) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardRealParameter.ProtoReflect.Descriptor instead.
func (*WizardRealParameter) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{1}
}

func (x *WizardRealParameter) GetValue() float64 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *WizardRealParameter) GetDefault() float64 {
	if x != nil {
		return x.Default
	}
	return 0
}

func (x *WizardRealParameter) GetMin() float64 {
	if x != nil && x.Min != nil {
		return *x.Min
	}
	return 0
}

func (x *WizardRealParameter) GetMax() float64 {
	if x != nil && x.Max != nil {
		return *x.Max
	}
	return 0
}

type WizardBoolParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Value         bool                   `protobuf:"varint,1,opt,name=value,proto3" json:"value,omitempty"`
	Default       bool                   `protobuf:"varint,2,opt,name=default,proto3" json:"default,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardBoolParameter) Reset() {
	*x = WizardBoolParameter{}
	mi := &file_common_types_wizards_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardBoolParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardBoolParameter) ProtoMessage() {}

func (x *WizardBoolParameter) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardBoolParameter.ProtoReflect.Descriptor instead.
func (*WizardBoolParameter) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{2}
}

func (x *WizardBoolParameter) GetValue() bool {
	if x != nil {
		return x.Value
	}
	return false
}

func (x *WizardBoolParameter) GetDefault() bool {
	if x != nil {
		return x.Default
	}
	return false
}

type WizardStringParameter struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Value           string                 `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	Default         string                 `protobuf:"bytes,2,opt,name=default,proto3" json:"default,omitempty"`
	ValidationRegex *string                `protobuf:"bytes,3,opt,name=validation_regex,json=validationRegex,proto3,oneof" json:"validation_regex,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *WizardStringParameter) Reset() {
	*x = WizardStringParameter{}
	mi := &file_common_types_wizards_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardStringParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardStringParameter) ProtoMessage() {}

func (x *WizardStringParameter) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardStringParameter.ProtoReflect.Descriptor instead.
func (*WizardStringParameter) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{3}
}

func (x *WizardStringParameter) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *WizardStringParameter) GetDefault() string {
	if x != nil {
		return x.Default
	}
	return ""
}

func (x *WizardStringParameter) GetValidationRegex() string {
	if x != nil && x.ValidationRegex != nil {
		return *x.ValidationRegex
	}
	return ""
}

type WizardParameterList struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Parameters    []*WizardParameter     `protobuf:"bytes,1,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardParameterList) Reset() {
	*x = WizardParameterList{}
	mi := &file_common_types_wizards_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardParameterList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardParameterList) ProtoMessage() {}

func (x *WizardParameterList) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardParameterList.ProtoReflect.Descriptor instead.
func (*WizardParameterList) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{4}
}

func (x *WizardParameterList) GetParameters() []*WizardParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type WizardParameter struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// An internal identifier for this parameter; must be unique within a wizard
	Identifier string `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	// The human-readable name for this parameter (may be translated)
	Name string `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// A human-readable description / tooltip string (may be translated)
	Description string                  `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Category    WizardParameterCategory `protobuf:"varint,4,opt,name=category,proto3,enum=kiapi.common.types.WizardParameterCategory" json:"category,omitempty"`
	Type        WizardParameterDataType `protobuf:"varint,5,opt,name=type,proto3,enum=kiapi.common.types.WizardParameterDataType" json:"type,omitempty"`
	// Types that are valid to be assigned to Value:
	//
	//	*WizardParameter_Int
	//	*WizardParameter_Real
	//	*WizardParameter_Bool
	//	*WizardParameter_String_
	Value         isWizardParameter_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardParameter) Reset() {
	*x = WizardParameter{}
	mi := &file_common_types_wizards_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardParameter) ProtoMessage() {}

func (x *WizardParameter) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardParameter.ProtoReflect.Descriptor instead.
func (*WizardParameter) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{5}
}

func (x *WizardParameter) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WizardParameter) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WizardParameter) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WizardParameter) GetCategory() WizardParameterCategory {
	if x != nil {
		return x.Category
	}
	return WizardParameterCategory_WPC_UNKNOWN
}

func (x *WizardParameter) GetType() WizardParameterDataType {
	if x != nil {
		return x.Type
	}
	return WizardParameterDataType_WPDT_UNKNOWN
}

func (x *WizardParameter) GetValue() isWizardParameter_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *WizardParameter) GetInt() *WizardIntParameter {
	if x != nil {
		if x, ok := x.Value.(*WizardParameter_Int); ok {
			return x.Int
		}
	}
	return nil
}

func (x *WizardParameter) GetReal() *WizardRealParameter {
	if x != nil {
		if x, ok := x.Value.(*WizardParameter_Real); ok {
			return x.Real
		}
	}
	return nil
}

func (x *WizardParameter) GetBool() *WizardBoolParameter {
	if x != nil {
		if x, ok := x.Value.(*WizardParameter_Bool); ok {
			return x.Bool
		}
	}
	return nil
}

func (x *WizardParameter) GetString_() *WizardStringParameter {
	if x != nil {
		if x, ok := x.Value.(*WizardParameter_String_); ok {
			return x.String_
		}
	}
	return nil
}

type isWizardParameter_Value interface {
	isWizardParameter_Value()
}

type WizardParameter_Int struct {
	Int *WizardIntParameter `protobuf:"bytes,6,opt,name=int,proto3,oneof"`
}

type WizardParameter_Real struct {
	Real *WizardRealParameter `protobuf:"bytes,7,opt,name=real,proto3,oneof"`
}

type WizardParameter_Bool struct {
	Bool *WizardBoolParameter `protobuf:"bytes,8,opt,name=bool,proto3,oneof"`
}

type WizardParameter_String_ struct {
	String_ *WizardStringParameter `protobuf:"bytes,9,opt,name=string,proto3,oneof"`
}

func (*WizardParameter_Int) isWizardParameter_Value() {}

func (*WizardParameter_Real) isWizardParameter_Value() {}

func (*WizardParameter_Bool) isWizardParameter_Value() {}

func (*WizardParameter_String_) isWizardParameter_Value() {}

type WizardInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *WizardMetaInfo        `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Parameters    []*WizardParameter     `protobuf:"bytes,2,rep,name=parameters,proto3" json:"parameters,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardInfo) Reset() {
	*x = WizardInfo{}
	mi := &file_common_types_wizards_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardInfo) ProtoMessage() {}

func (x *WizardInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardInfo.ProtoReflect.Descriptor instead.
func (*WizardInfo) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{6}
}

func (x *WizardInfo) GetMeta() *WizardMetaInfo {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *WizardInfo) GetParameters() []*WizardParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

type WizardMetaInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Identifier     string                 `protobuf:"bytes,1,opt,name=identifier,proto3" json:"identifier,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description    string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	TypesGenerated []WizardContentType    `protobuf:"varint,4,rep,packed,name=types_generated,json=typesGenerated,proto3,enum=kiapi.common.types.WizardContentType" json:"types_generated,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *WizardMetaInfo) Reset() {
	*x = WizardMetaInfo{}
	mi := &file_common_types_wizards_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardMetaInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardMetaInfo) ProtoMessage() {}

func (x *WizardMetaInfo) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardMetaInfo.ProtoReflect.Descriptor instead.
func (*WizardMetaInfo) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{7}
}

func (x *WizardMetaInfo) GetIdentifier() string {
	if x != nil {
		return x.Identifier
	}
	return ""
}

func (x *WizardMetaInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WizardMetaInfo) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *WizardMetaInfo) GetTypesGenerated() []WizardContentType {
	if x != nil {
		return x.TypesGenerated
	}
	return nil
}

type WizardGeneratedContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        WizardGenerationStatus `protobuf:"varint,1,opt,name=status,proto3,enum=kiapi.common.types.WizardGenerationStatus" json:"status,omitempty"`
	Content       *anypb.Any             `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	ErrorMessage  string                 `protobuf:"bytes,3,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WizardGeneratedContent) Reset() {
	*x = WizardGeneratedContent{}
	mi := &file_common_types_wizards_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WizardGeneratedContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WizardGeneratedContent) ProtoMessage() {}

func (x *WizardGeneratedContent) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_wizards_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WizardGeneratedContent.ProtoReflect.Descriptor instead.
func (*WizardGeneratedContent) Descriptor() ([]byte, []int) {
	return file_common_types_wizards_proto_rawDescGZIP(), []int{8}
}

func (x *WizardGeneratedContent) GetStatus() WizardGenerationStatus {
	if x != nil {
		return x.Status
	}
	return WizardGenerationStatus_WGS_UNKNOWN
}

func (x *WizardGeneratedContent) GetContent() *anypb.Any {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *WizardGeneratedContent) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

var File_common_types_wizards_proto protoreflect.FileDescriptor

const file_common_types_wizards_proto_rawDesc = "" +
	"\n" +
	"\x1acommon/types/wizards.proto\x12\x12kiapi.common.types\x1a\x19google/protobuf/any.proto\"\xb0\x01\n" +
	"\x12WizardIntParameter\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x05R\x05value\x12\x18\n" +
	"\adefault\x18\x02 \x01(\x05R\adefault\x12\x15\n" +
	"\x03min\x18\x03 \x01(\x05H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x04 \x01(\x05H\x01R\x03max\x88\x01\x01\x12\x1f\n" +
	"\bmultiple\x18\x05 \x01(\x05H\x02R\bmultiple\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_maxB\v\n" +
	"\t_multiple\"\x83\x01\n" +
	"\x13WizardRealParameter\x12\x14\n" +
	"\x05value\x18\x01 \x01(\x01R\x05value\x12\x18\n" +
	"\adefault\x18\x02 \x01(\x01R\adefault\x12\x15\n" +
	"\x03min\x18\x03 \x01(\x01H\x00R\x03min\x88\x01\x01\x12\x15\n" +
	"\x03max\x18\x04 \x01(\x01H\x01R\x03max\x88\x01\x01B\x06\n" +
	"\x04_minB\x06\n" +
	"\x04_max\"E\n" +
	"\x13WizardBoolParameter\x12\x14\n" +
	"\x05value\x18\x01 \x01(\bR\x05value\x12\x18\n" +
	"\adefault\x18\x02 \x01(\bR\adefault\"\x8c\x01\n" +
	"\x15WizardStringParameter\x12\x14\n" +
	"\x05value\x18\x01 \x01(\tR\x05value\x12\x18\n" +
	"\adefault\x18\x02 \x01(\tR\adefault\x12.\n" +
	"\x10validation_regex\x18\x03 \x01(\tH\x00R\x0fvalidationRegex\x88\x01\x01B\x13\n" +
	"\x11_validation_regex\"Z\n" +
	"\x13WizardParameterList\x12C\n" +
	"\n" +
	"parameters\x18\x01 \x03(\v2#.kiapi.common.types.WizardParameterR\n" +
	"parameters\"\xf9\x03\n" +
	"\x0fWizardParameter\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12G\n" +
	"\bcategory\x18\x04 \x01(\x0e2+.kiapi.common.types.WizardParameterCategoryR\bcategory\x12?\n" +
	"\x04type\x18\x05 \x01(\x0e2+.kiapi.common.types.WizardParameterDataTypeR\x04type\x12:\n" +
	"\x03int\x18\x06 \x01(\v2&.kiapi.common.types.WizardIntParameterH\x00R\x03int\x12=\n" +
	"\x04real\x18\a \x01(\v2'.kiapi.common.types.WizardRealParameterH\x00R\x04real\x12=\n" +
	"\x04bool\x18\b \x01(\v2'.kiapi.common.types.WizardBoolParameterH\x00R\x04bool\x12C\n" +
	"\x06string\x18\t \x01(\v2).kiapi.common.types.WizardStringParameterH\x00R\x06stringB\a\n" +
	"\x05value\"\x89\x01\n" +
	"\n" +
	"WizardInfo\x126\n" +
	"\x04meta\x18\x01 \x01(\v2\".kiapi.common.types.WizardMetaInfoR\x04meta\x12C\n" +
	"\n" +
	"parameters\x18\x02 \x03(\v2#.kiapi.common.types.WizardParameterR\n" +
	"parameters\"\xb6\x01\n" +
	"\x0eWizardMetaInfo\x12\x1e\n" +
	"\n" +
	"identifier\x18\x01 \x01(\tR\n" +
	"identifier\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12N\n" +
	"\x0ftypes_generated\x18\x04 \x03(\x0e2%.kiapi.common.types.WizardContentTypeR\x0etypesGenerated\"\xb1\x01\n" +
	"\x16WizardGeneratedContent\x12B\n" +
	"\x06status\x18\x01 \x01(\x0e2*.kiapi.common.types.WizardGenerationStatusR\x06status\x12.\n" +
	"\acontent\x18\x02 \x01(\v2\x14.google.protobuf.AnyR\acontent\x12#\n" +
	"\rerror_message\x18\x03 \x01(\tR\ferrorMessage*\xbe\x01\n" +
	"\x17WizardParameterDataType\x12\x10\n" +
	"\fWPDT_UNKNOWN\x10\x00\x12\x11\n" +
	"\rWPDT_DISTANCE\x10\x01\x12\r\n" +
	"\tWPDT_AREA\x10\x02\x12\x0f\n" +
	"\vWPDT_VOLUME\x10\x03\x12\r\n" +
	"\tWPDT_TIME\x10\x04\x12\x0e\n" +
	"\n" +
	"WPDT_ANGLE\x10\x05\x12\x0f\n" +
	"\vWPDT_STRING\x10\x06\x12\x10\n" +
	"\fWPDT_INTEGER\x10\a\x12\r\n" +
	"\tWPDT_REAL\x10\b\x12\r\n" +
	"\tWPDT_BOOL\x10\t*{\n" +
	"\x17WizardParameterCategory\x12\x0f\n" +
	"\vWPC_UNKNOWN\x10\x00\x12\x0f\n" +
	"\vWPC_PACKAGE\x10\x01\x12\f\n" +
	"\bWPC_PADS\x10\x02\x12\x0f\n" +
	"\vWPC_3DMODEL\x10\x03\x12\x10\n" +
	"\fWPC_METADATA\x10\x04\x12\r\n" +
	"\tWPC_RULES\x10\x05*G\n" +
	"\x11WizardContentType\x12\x0f\n" +
	"\vWCT_UNKNOWN\x10\x00\x12\x0e\n" +
	"\n" +
	"WCT_SYMBOL\x10\x01\x12\x11\n" +
	"\rWCT_FOOTPRINT\x10\x02*D\n" +
	"\x16WizardGenerationStatus\x12\x0f\n" +
	"\vWGS_UNKNOWN\x10\x00\x12\n" +
	"\n" +
	"\x06WGS_OK\x10\x01\x12\r\n" +
	"\tWGS_ERROR\x10\x02b\x06proto3"

var (
	file_common_types_wizards_proto_rawDescOnce sync.Once
	file_common_types_wizards_proto_rawDescData []byte
)

func file_common_types_wizards_proto_rawDescGZIP() []byte {
	file_common_types_wizards_proto_rawDescOnce.Do(func() {
		file_common_types_wizards_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_wizards_proto_rawDesc), len(file_common_types_wizards_proto_rawDesc)))
	})
	return file_common_types_wizards_proto_rawDescData
}

var file_common_types_wizards_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_common_types_wizards_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_common_types_wizards_proto_goTypes = []any{
	(WizardParameterDataType)(0),   // 0: kiapi.common.types.WizardParameterDataType
	(WizardParameterCategory)(0),   // 1: kiapi.common.types.WizardParameterCategory
	(WizardContentType)(0),         // 2: kiapi.common.types.WizardContentType
	(WizardGenerationStatus)(0),    // 3: kiapi.common.types.WizardGenerationStatus
	(*WizardIntParameter)(nil),     // 4: kiapi.common.types.WizardIntParameter
	(*WizardRealParameter)(nil),    // 5: kiapi.common.types.WizardRealParameter
	(*WizardBoolParameter)(nil),    // 6: kiapi.common.types.WizardBoolParameter
	(*WizardStringParameter)(nil),  // 7: kiapi.common.types.WizardStringParameter
	(*WizardParameterList)(nil),    // 8: kiapi.common.types.WizardParameterList
	(*WizardParameter)(nil),        // 9: kiapi.common.types.WizardParameter
	(*WizardInfo)(nil),             // 10: kiapi.common.types.WizardInfo
	(*WizardMetaInfo)(nil),         // 11: kiapi.common.types.WizardMetaInfo
	(*WizardGeneratedContent)(nil), // 12: kiapi.common.types.WizardGeneratedContent
	(*anypb.Any)(nil),              // 13: google.protobuf.Any
}
var file_common_types_wizards_proto_depIdxs = []int32{
	9,  // 0: kiapi.common.types.WizardParameterList.parameters:type_name -> kiapi.common.types.WizardParameter
	1,  // 1: kiapi.common.types.WizardParameter.category:type_name -> kiapi.common.types.WizardParameterCategory
	0,  // 2: kiapi.common.types.WizardParameter.type:type_name -> kiapi.common.types.WizardParameterDataType
	4,  // 3: kiapi.common.types.WizardParameter.int:type_name -> kiapi.common.types.WizardIntParameter
	5,  // 4: kiapi.common.types.WizardParameter.real:type_name -> kiapi.common.types.WizardRealParameter
	6,  // 5: kiapi.common.types.WizardParameter.bool:type_name -> kiapi.common.types.WizardBoolParameter
	7,  // 6: kiapi.common.types.WizardParameter.string:type_name -> kiapi.common.types.WizardStringParameter
	11, // 7: kiapi.common.types.WizardInfo.meta:type_name -> kiapi.common.types.WizardMetaInfo
	9,  // 8: kiapi.common.types.WizardInfo.parameters:type_name -> kiapi.common.types.WizardParameter
	2,  // 9: kiapi.common.types.WizardMetaInfo.types_generated:type_name -> kiapi.common.types.WizardContentType
	3,  // 10: kiapi.common.types.WizardGeneratedContent.status:type_name -> kiapi.common.types.WizardGenerationStatus
	13, // 11: kiapi.common.types.WizardGeneratedContent.content:type_name -> google.protobuf.Any
	12, // [12:12] is the sub-list for method output_type
	12, // [12:12] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_common_types_wizards_proto_init() }
func file_common_types_wizards_proto_init() {
	if File_common_types_wizards_proto != nil {
		return
	}
	file_common_types_wizards_proto_msgTypes[0].OneofWrappers = []any{}
	file_common_types_wizards_proto_msgTypes[1].OneofWrappers = []any{}
	file_common_types_wizards_proto_msgTypes[3].OneofWrappers = []any{}
	file_common_types_wizards_proto_msgTypes[5].OneofWrappers = []any{
		(*WizardParameter_Int)(nil),
		(*WizardParameter_Real)(nil),
		(*WizardParameter_Bool)(nil),
		(*WizardParameter_String_)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_wizards_proto_rawDesc), len(file_common_types_wizards_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_wizards_proto_goTypes,
		DependencyIndexes: file_common_types_wizards_proto_depIdxs,
		EnumInfos:         file_common_types_wizards_proto_enumTypes,
		MessageInfos:      file_common_types_wizards_proto_msgTypes,
	}.Build()
	File_common_types_wizards_proto = out.File
	file_common_types_wizards_proto_goTypes = nil
	file_common_types_wizards_proto_depIdxs = nil
}
