//
// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright (C) KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: schematic/schematic_jobs.proto

package schematic_jobs

import (
	jobs "github.com/eugenepentland/canopy_eda/tools/kicad-sync-go/internal/kicad/proto/common/types/jobs"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Page size override used for schematic plotting jobs
type SchematicJobPageSize int32

const (
	SchematicJobPageSize_SJPS_UNKNOWN SchematicJobPageSize = 0
	// Auto-select page size from sheet settings
	SchematicJobPageSize_SJPS_AUTO SchematicJobPageSize = 1
	// Force A4 page size
	SchematicJobPageSize_SJPS_A4 SchematicJobPageSize = 2
	// Force ANSI A page size
	SchematicJobPageSize_SJPS_A SchematicJobPageSize = 3
)

// Enum value maps for SchematicJobPageSize.
var (
	SchematicJobPageSize_name = map[int32]string{
		0: "SJPS_UNKNOWN",
		1: "SJPS_AUTO",
		2: "SJPS_A4",
		3: "SJPS_A",
	}
	SchematicJobPageSize_value = map[string]int32{
		"SJPS_UNKNOWN": 0,
		"SJPS_AUTO":    1,
		"SJPS_A4":      2,
		"SJPS_A":       3,
	}
)

func (x SchematicJobPageSize) Enum() *SchematicJobPageSize {
	p := new(SchematicJobPageSize)
	*p = x
	return p
}

func (x SchematicJobPageSize) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchematicJobPageSize) Descriptor() protoreflect.EnumDescriptor {
	return file_schematic_schematic_jobs_proto_enumTypes[0].Descriptor()
}

func (SchematicJobPageSize) Type() protoreflect.EnumType {
	return &file_schematic_schematic_jobs_proto_enumTypes[0]
}

func (x SchematicJobPageSize) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchematicJobPageSize.Descriptor instead.
func (SchematicJobPageSize) EnumDescriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{0}
}

// Netlist format for schematic netlist export.
type SchematicNetlistFormat int32

const (
	SchematicNetlistFormat_SNF_UNKNOWN     SchematicNetlistFormat = 0
	SchematicNetlistFormat_SNF_KICAD_XML   SchematicNetlistFormat = 1
	SchematicNetlistFormat_SNF_KICAD_SEXPR SchematicNetlistFormat = 2
	SchematicNetlistFormat_SNF_ORCAD_PCB2  SchematicNetlistFormat = 3
	SchematicNetlistFormat_SNF_CADSTAR     SchematicNetlistFormat = 4
	SchematicNetlistFormat_SNF_SPICE       SchematicNetlistFormat = 5
	SchematicNetlistFormat_SNF_SPICE_MODEL SchematicNetlistFormat = 6
	SchematicNetlistFormat_SNF_PADS        SchematicNetlistFormat = 7
	SchematicNetlistFormat_SNF_ALLEGRO     SchematicNetlistFormat = 8
)

// Enum value maps for SchematicNetlistFormat.
var (
	SchematicNetlistFormat_name = map[int32]string{
		0: "SNF_UNKNOWN",
		1: "SNF_KICAD_XML",
		2: "SNF_KICAD_SEXPR",
		3: "SNF_ORCAD_PCB2",
		4: "SNF_CADSTAR",
		5: "SNF_SPICE",
		6: "SNF_SPICE_MODEL",
		7: "SNF_PADS",
		8: "SNF_ALLEGRO",
	}
	SchematicNetlistFormat_value = map[string]int32{
		"SNF_UNKNOWN":     0,
		"SNF_KICAD_XML":   1,
		"SNF_KICAD_SEXPR": 2,
		"SNF_ORCAD_PCB2":  3,
		"SNF_CADSTAR":     4,
		"SNF_SPICE":       5,
		"SNF_SPICE_MODEL": 6,
		"SNF_PADS":        7,
		"SNF_ALLEGRO":     8,
	}
)

func (x SchematicNetlistFormat) Enum() *SchematicNetlistFormat {
	p := new(SchematicNetlistFormat)
	*p = x
	return p
}

func (x SchematicNetlistFormat) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SchematicNetlistFormat) Descriptor() protoreflect.EnumDescriptor {
	return file_schematic_schematic_jobs_proto_enumTypes[1].Descriptor()
}

func (SchematicNetlistFormat) Type() protoreflect.EnumType {
	return &file_schematic_schematic_jobs_proto_enumTypes[1]
}

func (x SchematicNetlistFormat) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SchematicNetlistFormat.Descriptor instead.
func (SchematicNetlistFormat) EnumDescriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{1}
}

type BOMSortDirection int32

const (
	BOMSortDirection_BSD_UNKNOWN    BOMSortDirection = 0
	BOMSortDirection_BSD_ASCENDING  BOMSortDirection = 1
	BOMSortDirection_BSD_DESCENDING BOMSortDirection = 2
)

// Enum value maps for BOMSortDirection.
var (
	BOMSortDirection_name = map[int32]string{
		0: "BSD_UNKNOWN",
		1: "BSD_ASCENDING",
		2: "BSD_DESCENDING",
	}
	BOMSortDirection_value = map[string]int32{
		"BSD_UNKNOWN":    0,
		"BSD_ASCENDING":  1,
		"BSD_DESCENDING": 2,
	}
)

func (x BOMSortDirection) Enum() *BOMSortDirection {
	p := new(BOMSortDirection)
	*p = x
	return p
}

func (x BOMSortDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (BOMSortDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_schematic_schematic_jobs_proto_enumTypes[2].Descriptor()
}

func (BOMSortDirection) Type() protoreflect.EnumType {
	return &file_schematic_schematic_jobs_proto_enumTypes[2]
}

func (x BOMSortDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use BOMSortDirection.Descriptor instead.
func (BOMSortDirection) EnumDescriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{2}
}

// Shared plot options for schematic plot exports
type SchematicPlotSettings struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DrawingSheet       string                 `protobuf:"bytes,1,opt,name=drawing_sheet,json=drawingSheet,proto3" json:"drawing_sheet,omitempty"`
	DefaultFont        string                 `protobuf:"bytes,2,opt,name=default_font,json=defaultFont,proto3" json:"default_font,omitempty"`
	Variant            string                 `protobuf:"bytes,3,opt,name=variant,proto3" json:"variant,omitempty"`
	PlotAll            bool                   `protobuf:"varint,4,opt,name=plot_all,json=plotAll,proto3" json:"plot_all,omitempty"`
	PlotDrawingSheet   bool                   `protobuf:"varint,5,opt,name=plot_drawing_sheet,json=plotDrawingSheet,proto3" json:"plot_drawing_sheet,omitempty"`
	PlotPages          []string               `protobuf:"bytes,6,rep,name=plot_pages,json=plotPages,proto3" json:"plot_pages,omitempty"`
	ShowHopOver        bool                   `protobuf:"varint,7,opt,name=show_hop_over,json=showHopOver,proto3" json:"show_hop_over,omitempty"`
	BlackAndWhite      bool                   `protobuf:"varint,8,opt,name=black_and_white,json=blackAndWhite,proto3" json:"black_and_white,omitempty"`
	PageSize           SchematicJobPageSize   `protobuf:"varint,9,opt,name=page_size,json=pageSize,proto3,enum=kiapi.schematic.jobs.SchematicJobPageSize" json:"page_size,omitempty"`
	UseBackgroundColor bool                   `protobuf:"varint,10,opt,name=use_background_color,json=useBackgroundColor,proto3" json:"use_background_color,omitempty"`
	MinPenWidth        int32                  `protobuf:"varint,11,opt,name=min_pen_width,json=minPenWidth,proto3" json:"min_pen_width,omitempty"`
	Theme              string                 `protobuf:"bytes,12,opt,name=theme,proto3" json:"theme,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *SchematicPlotSettings) Reset() {
	*x = SchematicPlotSettings{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchematicPlotSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchematicPlotSettings) ProtoMessage() {}

func (x *SchematicPlotSettings) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchematicPlotSettings.ProtoReflect.Descriptor instead.
func (*SchematicPlotSettings) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *SchematicPlotSettings) GetDrawingSheet() string {
	if x != nil {
		return x.DrawingSheet
	}
	return ""
}

func (x *SchematicPlotSettings) GetDefaultFont() string {
	if x != nil {
		return x.DefaultFont
	}
	return ""
}

func (x *SchematicPlotSettings) GetVariant() string {
	if x != nil {
		return x.Variant
	}
	return ""
}

func (x *SchematicPlotSettings) GetPlotAll() bool {
	if x != nil {
		return x.PlotAll
	}
	return false
}

func (x *SchematicPlotSettings) GetPlotDrawingSheet() bool {
	if x != nil {
		return x.PlotDrawingSheet
	}
	return false
}

func (x *SchematicPlotSettings) GetPlotPages() []string {
	if x != nil {
		return x.PlotPages
	}
	return nil
}

func (x *SchematicPlotSettings) GetShowHopOver() bool {
	if x != nil {
		return x.ShowHopOver
	}
	return false
}

func (x *SchematicPlotSettings) GetBlackAndWhite() bool {
	if x != nil {
		return x.BlackAndWhite
	}
	return false
}

func (x *SchematicPlotSettings) GetPageSize() SchematicJobPageSize {
	if x != nil {
		return x.PageSize
	}
	return SchematicJobPageSize_SJPS_UNKNOWN
}

func (x *SchematicPlotSettings) GetUseBackgroundColor() bool {
	if x != nil {
		return x.UseBackgroundColor
	}
	return false
}

func (x *SchematicPlotSettings) GetMinPenWidth() int32 {
	if x != nil {
		return x.MinPenWidth
	}
	return 0
}

func (x *SchematicPlotSettings) GetTheme() string {
	if x != nil {
		return x.Theme
	}
	return ""
}

// Plots a schematic to SVG. Returns RunJobResponse.
type RunSchematicJobExportSvg struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobSettings   *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	PlotSettings  *SchematicPlotSettings `protobuf:"bytes,2,opt,name=plot_settings,json=plotSettings,proto3" json:"plot_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchematicJobExportSvg) Reset() {
	*x = RunSchematicJobExportSvg{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportSvg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportSvg) ProtoMessage() {}

func (x *RunSchematicJobExportSvg) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportSvg.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportSvg) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *RunSchematicJobExportSvg) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportSvg) GetPlotSettings() *SchematicPlotSettings {
	if x != nil {
		return x.PlotSettings
	}
	return nil
}

// Plots a schematic to DXF. Returns RunJobResponse.
type RunSchematicJobExportDxf struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobSettings   *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	PlotSettings  *SchematicPlotSettings `protobuf:"bytes,2,opt,name=plot_settings,json=plotSettings,proto3" json:"plot_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchematicJobExportDxf) Reset() {
	*x = RunSchematicJobExportDxf{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportDxf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportDxf) ProtoMessage() {}

func (x *RunSchematicJobExportDxf) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportDxf.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportDxf) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{2}
}

func (x *RunSchematicJobExportDxf) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportDxf) GetPlotSettings() *SchematicPlotSettings {
	if x != nil {
		return x.PlotSettings
	}
	return nil
}

// Plots a schematic to PDF. Returns RunJobResponse.
type RunSchematicJobExportPdf struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	JobSettings       *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	PlotSettings      *SchematicPlotSettings `protobuf:"bytes,2,opt,name=plot_settings,json=plotSettings,proto3" json:"plot_settings,omitempty"`
	PropertyPopups    bool                   `protobuf:"varint,3,opt,name=property_popups,json=propertyPopups,proto3" json:"property_popups,omitempty"`
	HierarchicalLinks bool                   `protobuf:"varint,4,opt,name=hierarchical_links,json=hierarchicalLinks,proto3" json:"hierarchical_links,omitempty"`
	IncludeMetadata   bool                   `protobuf:"varint,5,opt,name=include_metadata,json=includeMetadata,proto3" json:"include_metadata,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *RunSchematicJobExportPdf) Reset() {
	*x = RunSchematicJobExportPdf{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportPdf) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportPdf) ProtoMessage() {}

func (x *RunSchematicJobExportPdf) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportPdf.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportPdf) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{3}
}

func (x *RunSchematicJobExportPdf) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportPdf) GetPlotSettings() *SchematicPlotSettings {
	if x != nil {
		return x.PlotSettings
	}
	return nil
}

func (x *RunSchematicJobExportPdf) GetPropertyPopups() bool {
	if x != nil {
		return x.PropertyPopups
	}
	return false
}

func (x *RunSchematicJobExportPdf) GetHierarchicalLinks() bool {
	if x != nil {
		return x.HierarchicalLinks
	}
	return false
}

func (x *RunSchematicJobExportPdf) GetIncludeMetadata() bool {
	if x != nil {
		return x.IncludeMetadata
	}
	return false
}

// Plots a schematic to PostScript. Returns RunJobResponse.
type RunSchematicJobExportPs struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	JobSettings   *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	PlotSettings  *SchematicPlotSettings `protobuf:"bytes,2,opt,name=plot_settings,json=plotSettings,proto3" json:"plot_settings,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchematicJobExportPs) Reset() {
	*x = RunSchematicJobExportPs{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportPs) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportPs) ProtoMessage() {}

func (x *RunSchematicJobExportPs) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportPs.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportPs) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{4}
}

func (x *RunSchematicJobExportPs) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportPs) GetPlotSettings() *SchematicPlotSettings {
	if x != nil {
		return x.PlotSettings
	}
	return nil
}

// Exports a schematic netlist. Returns RunJobResponse.
type RunSchematicJobExportNetlist struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobSettings *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	Format      SchematicNetlistFormat `protobuf:"varint,2,opt,name=format,proto3,enum=kiapi.schematic.jobs.SchematicNetlistFormat" json:"format,omitempty"`
	// If the design contains variants, this field can be set to the name of a variant to use
	// for the BOM export
	VariantName   string `protobuf:"bytes,3,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchematicJobExportNetlist) Reset() {
	*x = RunSchematicJobExportNetlist{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportNetlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportNetlist) ProtoMessage() {}

func (x *RunSchematicJobExportNetlist) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportNetlist.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportNetlist) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{5}
}

func (x *RunSchematicJobExportNetlist) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportNetlist) GetFormat() SchematicNetlistFormat {
	if x != nil {
		return x.Format
	}
	return SchematicNetlistFormat_SNF_UNKNOWN
}

func (x *RunSchematicJobExportNetlist) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

type BOMFormatSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If supplied, will apply a preset to the other format settings.  Built-in values 'CSV', 'TSV',
	// and 'Semicolons' are always available, as well as any user-saved presets.
	PresetName string `protobuf:"bytes,1,opt,name=preset_name,json=presetName,proto3" json:"preset_name,omitempty"`
	// Delimiter between fields (columns) in a data row
	FieldDelimiter string `protobuf:"bytes,2,opt,name=field_delimiter,json=fieldDelimiter,proto3" json:"field_delimiter,omitempty"`
	// Character to use for quoting strings
	StringDelimiter string `protobuf:"bytes,3,opt,name=string_delimiter,json=stringDelimiter,proto3" json:"string_delimiter,omitempty"`
	// Delimiter between reference designators when exporting a list (e.g. "R1,R3,R5")
	RefDelimiter string `protobuf:"bytes,4,opt,name=ref_delimiter,json=refDelimiter,proto3" json:"ref_delimiter,omitempty"`
	// Delimiter between reference designators when exporting a range (e.g. "R1-R10")
	RefRangeDelimiter string `protobuf:"bytes,5,opt,name=ref_range_delimiter,json=refRangeDelimiter,proto3" json:"ref_range_delimiter,omitempty"`
	// Whether tab characters in field values will be preserved when exporting or stripped (default)
	KeepTabs bool `protobuf:"varint,6,opt,name=keep_tabs,json=keepTabs,proto3" json:"keep_tabs,omitempty"`
	// Whether line breaks in field values will be preserved when exporting or stripped (default)
	KeepLineBreaks bool `protobuf:"varint,7,opt,name=keep_line_breaks,json=keepLineBreaks,proto3" json:"keep_line_breaks,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *BOMFormatSettings) Reset() {
	*x = BOMFormatSettings{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BOMFormatSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOMFormatSettings) ProtoMessage() {}

func (x *BOMFormatSettings) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOMFormatSettings.ProtoReflect.Descriptor instead.
func (*BOMFormatSettings) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{6}
}

func (x *BOMFormatSettings) GetPresetName() string {
	if x != nil {
		return x.PresetName
	}
	return ""
}

func (x *BOMFormatSettings) GetFieldDelimiter() string {
	if x != nil {
		return x.FieldDelimiter
	}
	return ""
}

func (x *BOMFormatSettings) GetStringDelimiter() string {
	if x != nil {
		return x.StringDelimiter
	}
	return ""
}

func (x *BOMFormatSettings) GetRefDelimiter() string {
	if x != nil {
		return x.RefDelimiter
	}
	return ""
}

func (x *BOMFormatSettings) GetRefRangeDelimiter() string {
	if x != nil {
		return x.RefRangeDelimiter
	}
	return ""
}

func (x *BOMFormatSettings) GetKeepTabs() bool {
	if x != nil {
		return x.KeepTabs
	}
	return false
}

func (x *BOMFormatSettings) GetKeepLineBreaks() bool {
	if x != nil {
		return x.KeepLineBreaks
	}
	return false
}

type BOMField struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The name of the field in KiCad to export
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The name to give the field in the exported BOM (i.e. the column header name)
	Label string `protobuf:"bytes,2,opt,name=label,proto3" json:"label,omitempty"`
	// Whether or not to group exported components by this field
	GroupBy       bool `protobuf:"varint,3,opt,name=group_by,json=groupBy,proto3" json:"group_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BOMField) Reset() {
	*x = BOMField{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BOMField) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOMField) ProtoMessage() {}

func (x *BOMField) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOMField.ProtoReflect.Descriptor instead.
func (*BOMField) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{7}
}

func (x *BOMField) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BOMField) GetLabel() string {
	if x != nil {
		return x.Label
	}
	return ""
}

func (x *BOMField) GetGroupBy() bool {
	if x != nil {
		return x.GroupBy
	}
	return false
}

type BOMFieldSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// If supplied, will apply a default or user-stored preset to the other field settings.
	// Default values available include 'Default Editing', 'Grouped By Value',
	// 'Grouped By Value and Footprint', and 'Attributes'.
	PresetName string `protobuf:"bytes,1,opt,name=preset_name,json=presetName,proto3" json:"preset_name,omitempty"`
	// An ordered list of fields to export
	Fields    []*BOMField `protobuf:"bytes,2,rep,name=fields,proto3" json:"fields,omitempty"`
	SortField string      `protobuf:"bytes,3,opt,name=sort_field,json=sortField,proto3" json:"sort_field,omitempty"`
	// Sort direction; defaults to ascending if unspecified
	SortDirection BOMSortDirection `protobuf:"varint,4,opt,name=sort_direction,json=sortDirection,proto3,enum=kiapi.schematic.jobs.BOMSortDirection" json:"sort_direction,omitempty"`
	Filter        string           `protobuf:"bytes,5,opt,name=filter,proto3" json:"filter,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BOMFieldSettings) Reset() {
	*x = BOMFieldSettings{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BOMFieldSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BOMFieldSettings) ProtoMessage() {}

func (x *BOMFieldSettings) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BOMFieldSettings.ProtoReflect.Descriptor instead.
func (*BOMFieldSettings) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{8}
}

func (x *BOMFieldSettings) GetPresetName() string {
	if x != nil {
		return x.PresetName
	}
	return ""
}

func (x *BOMFieldSettings) GetFields() []*BOMField {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *BOMFieldSettings) GetSortField() string {
	if x != nil {
		return x.SortField
	}
	return ""
}

func (x *BOMFieldSettings) GetSortDirection() BOMSortDirection {
	if x != nil {
		return x.SortDirection
	}
	return BOMSortDirection_BSD_UNKNOWN
}

func (x *BOMFieldSettings) GetFilter() string {
	if x != nil {
		return x.Filter
	}
	return ""
}

// Exports a schematic bill of materials. Returns RunJobResponse.
type RunSchematicJobExportBOM struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	JobSettings *jobs.RunJobSettings   `protobuf:"bytes,1,opt,name=job_settings,json=jobSettings,proto3" json:"job_settings,omitempty"`
	Format      *BOMFormatSettings     `protobuf:"bytes,2,opt,name=format,proto3" json:"format,omitempty"`
	Fields      *BOMFieldSettings      `protobuf:"bytes,3,opt,name=fields,proto3" json:"fields,omitempty"`
	// If true, "do not populate" components will be omitted from the exported BOM
	ExcludeDnp bool `protobuf:"varint,4,opt,name=exclude_dnp,json=excludeDnp,proto3" json:"exclude_dnp,omitempty"`
	// If true, will group symbols into a single BOM row when they have matching values for any
	// fields where group_by is true
	GroupSymbols bool `protobuf:"varint,5,opt,name=group_symbols,json=groupSymbols,proto3" json:"group_symbols,omitempty"`
	// If the design contains variants, this field can be set to the name of a variant to use
	// for the BOM export
	VariantName   string `protobuf:"bytes,6,opt,name=variant_name,json=variantName,proto3" json:"variant_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunSchematicJobExportBOM) Reset() {
	*x = RunSchematicJobExportBOM{}
	mi := &file_schematic_schematic_jobs_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunSchematicJobExportBOM) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunSchematicJobExportBOM) ProtoMessage() {}

func (x *RunSchematicJobExportBOM) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_jobs_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunSchematicJobExportBOM.ProtoReflect.Descriptor instead.
func (*RunSchematicJobExportBOM) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_jobs_proto_rawDescGZIP(), []int{9}
}

func (x *RunSchematicJobExportBOM) GetJobSettings() *jobs.RunJobSettings {
	if x != nil {
		return x.JobSettings
	}
	return nil
}

func (x *RunSchematicJobExportBOM) GetFormat() *BOMFormatSettings {
	if x != nil {
		return x.Format
	}
	return nil
}

func (x *RunSchematicJobExportBOM) GetFields() *BOMFieldSettings {
	if x != nil {
		return x.Fields
	}
	return nil
}

func (x *RunSchematicJobExportBOM) GetExcludeDnp() bool {
	if x != nil {
		return x.ExcludeDnp
	}
	return false
}

func (x *RunSchematicJobExportBOM) GetGroupSymbols() bool {
	if x != nil {
		return x.GroupSymbols
	}
	return false
}

func (x *RunSchematicJobExportBOM) GetVariantName() string {
	if x != nil {
		return x.VariantName
	}
	return ""
}

var File_schematic_schematic_jobs_proto protoreflect.FileDescriptor

const file_schematic_schematic_jobs_proto_rawDesc = "" +
	"\n" +
	"\x1eschematic/schematic_jobs.proto\x12\x14kiapi.schematic.jobs\x1a\x17common/types/jobs.proto\"\xe2\x03\n" +
	"\x15SchematicPlotSettings\x12#\n" +
	"\rdrawing_sheet\x18\x01 \x01(\tR\fdrawingSheet\x12!\n" +
	"\fdefault_font\x18\x02 \x01(\tR\vdefaultFont\x12\x18\n" +
	"\avariant\x18\x03 \x01(\tR\avariant\x12\x19\n" +
	"\bplot_all\x18\x04 \x01(\bR\aplotAll\x12,\n" +
	"\x12plot_drawing_sheet\x18\x05 \x01(\bR\x10plotDrawingSheet\x12\x1d\n" +
	"\n" +
	"plot_pages\x18\x06 \x03(\tR\tplotPages\x12\"\n" +
	"\rshow_hop_over\x18\a \x01(\bR\vshowHopOver\x12&\n" +
	"\x0fblack_and_white\x18\b \x01(\bR\rblackAndWhite\x12G\n" +
	"\tpage_size\x18\t \x01(\x0e2*.kiapi.schematic.jobs.SchematicJobPageSizeR\bpageSize\x120\n" +
	"\x14use_background_color\x18\n" +
	" \x01(\bR\x12useBackgroundColor\x12\"\n" +
	"\rmin_pen_width\x18\v \x01(\x05R\vminPenWidth\x12\x14\n" +
	"\x05theme\x18\f \x01(\tR\x05theme\"\xb3\x01\n" +
	"\x18RunSchematicJobExportSvg\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12P\n" +
	"\rplot_settings\x18\x02 \x01(\v2+.kiapi.schematic.jobs.SchematicPlotSettingsR\fplotSettings\"\xb3\x01\n" +
	"\x18RunSchematicJobExportDxf\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12P\n" +
	"\rplot_settings\x18\x02 \x01(\v2+.kiapi.schematic.jobs.SchematicPlotSettingsR\fplotSettings\"\xb6\x02\n" +
	"\x18RunSchematicJobExportPdf\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12P\n" +
	"\rplot_settings\x18\x02 \x01(\v2+.kiapi.schematic.jobs.SchematicPlotSettingsR\fplotSettings\x12'\n" +
	"\x0fproperty_popups\x18\x03 \x01(\bR\x0epropertyPopups\x12-\n" +
	"\x12hierarchical_links\x18\x04 \x01(\bR\x11hierarchicalLinks\x12)\n" +
	"\x10include_metadata\x18\x05 \x01(\bR\x0fincludeMetadata\"\xb2\x01\n" +
	"\x17RunSchematicJobExportPs\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12P\n" +
	"\rplot_settings\x18\x02 \x01(\v2+.kiapi.schematic.jobs.SchematicPlotSettingsR\fplotSettings\"\xce\x01\n" +
	"\x1cRunSchematicJobExportNetlist\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12D\n" +
	"\x06format\x18\x02 \x01(\x0e2,.kiapi.schematic.jobs.SchematicNetlistFormatR\x06format\x12!\n" +
	"\fvariant_name\x18\x03 \x01(\tR\vvariantName\"\xa4\x02\n" +
	"\x11BOMFormatSettings\x12\x1f\n" +
	"\vpreset_name\x18\x01 \x01(\tR\n" +
	"presetName\x12'\n" +
	"\x0ffield_delimiter\x18\x02 \x01(\tR\x0efieldDelimiter\x12)\n" +
	"\x10string_delimiter\x18\x03 \x01(\tR\x0fstringDelimiter\x12#\n" +
	"\rref_delimiter\x18\x04 \x01(\tR\frefDelimiter\x12.\n" +
	"\x13ref_range_delimiter\x18\x05 \x01(\tR\x11refRangeDelimiter\x12\x1b\n" +
	"\tkeep_tabs\x18\x06 \x01(\bR\bkeepTabs\x12(\n" +
	"\x10keep_line_breaks\x18\a \x01(\bR\x0ekeepLineBreaks\"O\n" +
	"\bBOMField\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05label\x18\x02 \x01(\tR\x05label\x12\x19\n" +
	"\bgroup_by\x18\x03 \x01(\bR\agroupBy\"\xf1\x01\n" +
	"\x10BOMFieldSettings\x12\x1f\n" +
	"\vpreset_name\x18\x01 \x01(\tR\n" +
	"presetName\x126\n" +
	"\x06fields\x18\x02 \x03(\v2\x1e.kiapi.schematic.jobs.BOMFieldR\x06fields\x12\x1d\n" +
	"\n" +
	"sort_field\x18\x03 \x01(\tR\tsortField\x12M\n" +
	"\x0esort_direction\x18\x04 \x01(\x0e2&.kiapi.schematic.jobs.BOMSortDirectionR\rsortDirection\x12\x16\n" +
	"\x06filter\x18\x05 \x01(\tR\x06filter\"\xcb\x02\n" +
	"\x18RunSchematicJobExportBOM\x12E\n" +
	"\fjob_settings\x18\x01 \x01(\v2\".kiapi.common.types.RunJobSettingsR\vjobSettings\x12?\n" +
	"\x06format\x18\x02 \x01(\v2'.kiapi.schematic.jobs.BOMFormatSettingsR\x06format\x12>\n" +
	"\x06fields\x18\x03 \x01(\v2&.kiapi.schematic.jobs.BOMFieldSettingsR\x06fields\x12\x1f\n" +
	"\vexclude_dnp\x18\x04 \x01(\bR\n" +
	"excludeDnp\x12#\n" +
	"\rgroup_symbols\x18\x05 \x01(\bR\fgroupSymbols\x12!\n" +
	"\fvariant_name\x18\x06 \x01(\tR\vvariantName*P\n" +
	"\x14SchematicJobPageSize\x12\x10\n" +
	"\fSJPS_UNKNOWN\x10\x00\x12\r\n" +
	"\tSJPS_AUTO\x10\x01\x12\v\n" +
	"\aSJPS_A4\x10\x02\x12\n" +
	"\n" +
	"\x06SJPS_A\x10\x03*\xb9\x01\n" +
	"\x16SchematicNetlistFormat\x12\x0f\n" +
	"\vSNF_UNKNOWN\x10\x00\x12\x11\n" +
	"\rSNF_KICAD_XML\x10\x01\x12\x13\n" +
	"\x0fSNF_KICAD_SEXPR\x10\x02\x12\x12\n" +
	"\x0eSNF_ORCAD_PCB2\x10\x03\x12\x0f\n" +
	"\vSNF_CADSTAR\x10\x04\x12\r\n" +
	"\tSNF_SPICE\x10\x05\x12\x13\n" +
	"\x0fSNF_SPICE_MODEL\x10\x06\x12\f\n" +
	"\bSNF_PADS\x10\a\x12\x0f\n" +
	"\vSNF_ALLEGRO\x10\b*J\n" +
	"\x10BOMSortDirection\x12\x0f\n" +
	"\vBSD_UNKNOWN\x10\x00\x12\x11\n" +
	"\rBSD_ASCENDING\x10\x01\x12\x12\n" +
	"\x0eBSD_DESCENDING\x10\x02b\x06proto3"

var (
	file_schematic_schematic_jobs_proto_rawDescOnce sync.Once
	file_schematic_schematic_jobs_proto_rawDescData []byte
)

func file_schematic_schematic_jobs_proto_rawDescGZIP() []byte {
	file_schematic_schematic_jobs_proto_rawDescOnce.Do(func() {
		file_schematic_schematic_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schematic_schematic_jobs_proto_rawDesc), len(file_schematic_schematic_jobs_proto_rawDesc)))
	})
	return file_schematic_schematic_jobs_proto_rawDescData
}

var file_schematic_schematic_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_schematic_schematic_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 10)
var file_schematic_schematic_jobs_proto_goTypes = []any{
	(SchematicJobPageSize)(0),            // 0: kiapi.schematic.jobs.SchematicJobPageSize
	(SchematicNetlistFormat)(0),          // 1: kiapi.schematic.jobs.SchematicNetlistFormat
	(BOMSortDirection)(0),                // 2: kiapi.schematic.jobs.BOMSortDirection
	(*SchematicPlotSettings)(nil),        // 3: kiapi.schematic.jobs.SchematicPlotSettings
	(*RunSchematicJobExportSvg)(nil),     // 4: kiapi.schematic.jobs.RunSchematicJobExportSvg
	(*RunSchematicJobExportDxf)(nil),     // 5: kiapi.schematic.jobs.RunSchematicJobExportDxf
	(*RunSchematicJobExportPdf)(nil),     // 6: kiapi.schematic.jobs.RunSchematicJobExportPdf
	(*RunSchematicJobExportPs)(nil),      // 7: kiapi.schematic.jobs.RunSchematicJobExportPs
	(*RunSchematicJobExportNetlist)(nil), // 8: kiapi.schematic.jobs.RunSchematicJobExportNetlist
	(*BOMFormatSettings)(nil),            // 9: kiapi.schematic.jobs.BOMFormatSettings
	(*BOMField)(nil),                     // 10: kiapi.schematic.jobs.BOMField
	(*BOMFieldSettings)(nil),             // 11: kiapi.schematic.jobs.BOMFieldSettings
	(*RunSchematicJobExportBOM)(nil),     // 12: kiapi.schematic.jobs.RunSchematicJobExportBOM
	(*jobs.RunJobSettings)(nil),          // 13: kiapi.common.types.RunJobSettings
}
var file_schematic_schematic_jobs_proto_depIdxs = []int32{
	0,  // 0: kiapi.schematic.jobs.SchematicPlotSettings.page_size:type_name -> kiapi.schematic.jobs.SchematicJobPageSize
	13, // 1: kiapi.schematic.jobs.RunSchematicJobExportSvg.job_settings:type_name -> kiapi.common.types.RunJobSettings
	3,  // 2: kiapi.schematic.jobs.RunSchematicJobExportSvg.plot_settings:type_name -> kiapi.schematic.jobs.SchematicPlotSettings
	13, // 3: kiapi.schematic.jobs.RunSchematicJobExportDxf.job_settings:type_name -> kiapi.common.types.RunJobSettings
	3,  // 4: kiapi.schematic.jobs.RunSchematicJobExportDxf.plot_settings:type_name -> kiapi.schematic.jobs.SchematicPlotSettings
	13, // 5: kiapi.schematic.jobs.RunSchematicJobExportPdf.job_settings:type_name -> kiapi.common.types.RunJobSettings
	3,  // 6: kiapi.schematic.jobs.RunSchematicJobExportPdf.plot_settings:type_name -> kiapi.schematic.jobs.SchematicPlotSettings
	13, // 7: kiapi.schematic.jobs.RunSchematicJobExportPs.job_settings:type_name -> kiapi.common.types.RunJobSettings
	3,  // 8: kiapi.schematic.jobs.RunSchematicJobExportPs.plot_settings:type_name -> kiapi.schematic.jobs.SchematicPlotSettings
	13, // 9: kiapi.schematic.jobs.RunSchematicJobExportNetlist.job_settings:type_name -> kiapi.common.types.RunJobSettings
	1,  // 10: kiapi.schematic.jobs.RunSchematicJobExportNetlist.format:type_name -> kiapi.schematic.jobs.SchematicNetlistFormat
	10, // 11: kiapi.schematic.jobs.BOMFieldSettings.fields:type_name -> kiapi.schematic.jobs.BOMField
	2,  // 12: kiapi.schematic.jobs.BOMFieldSettings.sort_direction:type_name -> kiapi.schematic.jobs.BOMSortDirection
	13, // 13: kiapi.schematic.jobs.RunSchematicJobExportBOM.job_settings:type_name -> kiapi.common.types.RunJobSettings
	9,  // 14: kiapi.schematic.jobs.RunSchematicJobExportBOM.format:type_name -> kiapi.schematic.jobs.BOMFormatSettings
	11, // 15: kiapi.schematic.jobs.RunSchematicJobExportBOM.fields:type_name -> kiapi.schematic.jobs.BOMFieldSettings
	16, // [16:16] is the sub-list for method output_type
	16, // [16:16] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_schematic_schematic_jobs_proto_init() }
func file_schematic_schematic_jobs_proto_init() {
	if File_schematic_schematic_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schematic_schematic_jobs_proto_rawDesc), len(file_schematic_schematic_jobs_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   10,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schematic_schematic_jobs_proto_goTypes,
		DependencyIndexes: file_schematic_schematic_jobs_proto_depIdxs,
		EnumInfos:         file_schematic_schematic_jobs_proto_enumTypes,
		MessageInfos:      file_schematic_schematic_jobs_proto_msgTypes,
	}.Build()
	File_schematic_schematic_jobs_proto = out.File
	file_schematic_schematic_jobs_proto_goTypes = nil
	file_schematic_schematic_jobs_proto_depIdxs = nil
}
