//
// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright (C) 2024 KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: schematic/schematic_commands.proto

package schematic_commands

import (
	base_types "github.com/eugenepentland/canvas_eda/tools/kicad-sync-go/internal/kicad/proto/common/types/base_types"
	enums "github.com/eugenepentland/canvas_eda/tools/kicad-sync-go/internal/kicad/proto/common/types/enums"
	schematic_types "github.com/eugenepentland/canvas_eda/tools/kicad-sync-go/internal/kicad/proto/schematic/schematic_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GetSchematicHierarchy struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type must be DT_SCHEMATIC and only the project is considered
	Document      *base_types.DocumentSpecifier `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchematicHierarchy) Reset() {
	*x = GetSchematicHierarchy{}
	mi := &file_schematic_schematic_commands_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchematicHierarchy) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchematicHierarchy) ProtoMessage() {}

func (x *GetSchematicHierarchy) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_commands_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchematicHierarchy.ProtoReflect.Descriptor instead.
func (*GetSchematicHierarchy) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_commands_proto_rawDescGZIP(), []int{0}
}

func (x *GetSchematicHierarchy) GetDocument() *base_types.DocumentSpecifier {
	if x != nil {
		return x.Document
	}
	return nil
}

type SchematicHierarchyResponse struct {
	state          protoimpl.MessageState           `protogen:"open.v1"`
	Document       *base_types.DocumentSpecifier    `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	TopLevelSheets []*schematic_types.SheetInstance `protobuf:"bytes,2,rep,name=top_level_sheets,json=topLevelSheets,proto3" json:"top_level_sheets,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *SchematicHierarchyResponse) Reset() {
	*x = SchematicHierarchyResponse{}
	mi := &file_schematic_schematic_commands_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchematicHierarchyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchematicHierarchyResponse) ProtoMessage() {}

func (x *SchematicHierarchyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_commands_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchematicHierarchyResponse.ProtoReflect.Descriptor instead.
func (*SchematicHierarchyResponse) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_commands_proto_rawDescGZIP(), []int{1}
}

func (x *SchematicHierarchyResponse) GetDocument() *base_types.DocumentSpecifier {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SchematicHierarchyResponse) GetTopLevelSheets() []*schematic_types.SheetInstance {
	if x != nil {
		return x.TopLevelSheets
	}
	return nil
}

// Returns SchematicNetlistResponse
type GetSchematicNetlist struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Type must be DT_SCHEMATIC and only the project is considered
	Document *base_types.DocumentSpecifier `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// Optional filter for types of items to return in SchematicNetSheetContents items fields.
	// If not specified, all types will be returned.  Only connectable schematic items are valid
	// here (pins, labels, wires, etc).
	Types         []enums.KiCadObjectType `protobuf:"varint,2,rep,packed,name=types,proto3,enum=kiapi.common.types.KiCadObjectType" json:"types,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSchematicNetlist) Reset() {
	*x = GetSchematicNetlist{}
	mi := &file_schematic_schematic_commands_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSchematicNetlist) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSchematicNetlist) ProtoMessage() {}

func (x *GetSchematicNetlist) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_commands_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSchematicNetlist.ProtoReflect.Descriptor instead.
func (*GetSchematicNetlist) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_commands_proto_rawDescGZIP(), []int{2}
}

func (x *GetSchematicNetlist) GetDocument() *base_types.DocumentSpecifier {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *GetSchematicNetlist) GetTypes() []enums.KiCadObjectType {
	if x != nil {
		return x.Types
	}
	return nil
}

type SchematicNetlistResponse struct {
	state         protoimpl.MessageState          `protogen:"open.v1"`
	Document      *base_types.DocumentSpecifier   `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	Nets          []*schematic_types.SchematicNet `protobuf:"bytes,2,rep,name=nets,proto3" json:"nets,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SchematicNetlistResponse) Reset() {
	*x = SchematicNetlistResponse{}
	mi := &file_schematic_schematic_commands_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SchematicNetlistResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SchematicNetlistResponse) ProtoMessage() {}

func (x *SchematicNetlistResponse) ProtoReflect() protoreflect.Message {
	mi := &file_schematic_schematic_commands_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SchematicNetlistResponse.ProtoReflect.Descriptor instead.
func (*SchematicNetlistResponse) Descriptor() ([]byte, []int) {
	return file_schematic_schematic_commands_proto_rawDescGZIP(), []int{3}
}

func (x *SchematicNetlistResponse) GetDocument() *base_types.DocumentSpecifier {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *SchematicNetlistResponse) GetNets() []*schematic_types.SchematicNet {
	if x != nil {
		return x.Nets
	}
	return nil
}

var File_schematic_schematic_commands_proto protoreflect.FileDescriptor

const file_schematic_schematic_commands_proto_rawDesc = "" +
	"\n" +
	"\"schematic/schematic_commands.proto\x12\x15kiapi.schematic.types\x1a\x1dcommon/types/base_types.proto\x1a\x18common/types/enums.proto\x1a\x1fschematic/schematic_types.proto\"Z\n" +
	"\x15GetSchematicHierarchy\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.kiapi.common.types.DocumentSpecifierR\bdocument\"\xaf\x01\n" +
	"\x1aSchematicHierarchyResponse\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.kiapi.common.types.DocumentSpecifierR\bdocument\x12N\n" +
	"\x10top_level_sheets\x18\x02 \x03(\v2$.kiapi.schematic.types.SheetInstanceR\x0etopLevelSheets\"\x93\x01\n" +
	"\x13GetSchematicNetlist\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.kiapi.common.types.DocumentSpecifierR\bdocument\x129\n" +
	"\x05types\x18\x02 \x03(\x0e2#.kiapi.common.types.KiCadObjectTypeR\x05types\"\x96\x01\n" +
	"\x18SchematicNetlistResponse\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.kiapi.common.types.DocumentSpecifierR\bdocument\x127\n" +
	"\x04nets\x18\x02 \x03(\v2#.kiapi.schematic.types.SchematicNetR\x04netsb\x06proto3"

var (
	file_schematic_schematic_commands_proto_rawDescOnce sync.Once
	file_schematic_schematic_commands_proto_rawDescData []byte
)

func file_schematic_schematic_commands_proto_rawDescGZIP() []byte {
	file_schematic_schematic_commands_proto_rawDescOnce.Do(func() {
		file_schematic_schematic_commands_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_schematic_schematic_commands_proto_rawDesc), len(file_schematic_schematic_commands_proto_rawDesc)))
	})
	return file_schematic_schematic_commands_proto_rawDescData
}

var file_schematic_schematic_commands_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_schematic_schematic_commands_proto_goTypes = []any{
	(*GetSchematicHierarchy)(nil),         // 0: kiapi.schematic.types.GetSchematicHierarchy
	(*SchematicHierarchyResponse)(nil),    // 1: kiapi.schematic.types.SchematicHierarchyResponse
	(*GetSchematicNetlist)(nil),           // 2: kiapi.schematic.types.GetSchematicNetlist
	(*SchematicNetlistResponse)(nil),      // 3: kiapi.schematic.types.SchematicNetlistResponse
	(*base_types.DocumentSpecifier)(nil),  // 4: kiapi.common.types.DocumentSpecifier
	(*schematic_types.SheetInstance)(nil), // 5: kiapi.schematic.types.SheetInstance
	(enums.KiCadObjectType)(0),            // 6: kiapi.common.types.KiCadObjectType
	(*schematic_types.SchematicNet)(nil),  // 7: kiapi.schematic.types.SchematicNet
}
var file_schematic_schematic_commands_proto_depIdxs = []int32{
	4, // 0: kiapi.schematic.types.GetSchematicHierarchy.document:type_name -> kiapi.common.types.DocumentSpecifier
	4, // 1: kiapi.schematic.types.SchematicHierarchyResponse.document:type_name -> kiapi.common.types.DocumentSpecifier
	5, // 2: kiapi.schematic.types.SchematicHierarchyResponse.top_level_sheets:type_name -> kiapi.schematic.types.SheetInstance
	4, // 3: kiapi.schematic.types.GetSchematicNetlist.document:type_name -> kiapi.common.types.DocumentSpecifier
	6, // 4: kiapi.schematic.types.GetSchematicNetlist.types:type_name -> kiapi.common.types.KiCadObjectType
	4, // 5: kiapi.schematic.types.SchematicNetlistResponse.document:type_name -> kiapi.common.types.DocumentSpecifier
	7, // 6: kiapi.schematic.types.SchematicNetlistResponse.nets:type_name -> kiapi.schematic.types.SchematicNet
	7, // [7:7] is the sub-list for method output_type
	7, // [7:7] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_schematic_schematic_commands_proto_init() }
func file_schematic_schematic_commands_proto_init() {
	if File_schematic_schematic_commands_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_schematic_schematic_commands_proto_rawDesc), len(file_schematic_schematic_commands_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_schematic_schematic_commands_proto_goTypes,
		DependencyIndexes: file_schematic_schematic_commands_proto_depIdxs,
		MessageInfos:      file_schematic_schematic_commands_proto_msgTypes,
	}.Build()
	File_schematic_schematic_commands_proto = out.File
	file_schematic_schematic_commands_proto_goTypes = nil
	file_schematic_schematic_commands_proto_depIdxs = nil
}
