//
// This program source code file is part of KiCad, a free EDA CAD application.
//
// Copyright (C) KiCad Developers, see AUTHORS.txt for contributors.
//
// This program is free software: you can redistribute it and/or modify it
// under the terms of the GNU General Public License as published by the
// Free Software Foundation, either version 3 of the License, or (at your
// option) any later version.
//
// This program is distributed in the hope that it will be useful, but
// WITHOUT ANY WARRANTY; without even the implied warranty of
// MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
// General Public License for more details.
//
// You should have received a copy of the GNU General Public License along
// with this program.  If not, see <http://www.gnu.org/licenses/>.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.30.2
// source: common/types/jobs.proto

package jobs

import (
	base_types "github.com/eugenepentland/canvas_eda/tools/kicad-sync-go/internal/kicad/proto/common/types/base_types"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type JobStatus int32

const (
	JobStatus_JS_UNSPECIFIED JobStatus = 0
	JobStatus_JS_SUCCESS     JobStatus = 1
	JobStatus_JS_WARNING     JobStatus = 2
	JobStatus_JS_ERROR       JobStatus = 3
)

// Enum value maps for JobStatus.
var (
	JobStatus_name = map[int32]string{
		0: "JS_UNSPECIFIED",
		1: "JS_SUCCESS",
		2: "JS_WARNING",
		3: "JS_ERROR",
	}
	JobStatus_value = map[string]int32{
		"JS_UNSPECIFIED": 0,
		"JS_SUCCESS":     1,
		"JS_WARNING":     2,
		"JS_ERROR":       3,
	}
)

func (x JobStatus) Enum() *JobStatus {
	p := new(JobStatus)
	*p = x
	return p
}

func (x JobStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (JobStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_common_types_jobs_proto_enumTypes[0].Descriptor()
}

func (JobStatus) Type() protoreflect.EnumType {
	return &file_common_types_jobs_proto_enumTypes[0]
}

func (x JobStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use JobStatus.Descriptor instead.
func (JobStatus) EnumDescriptor() ([]byte, []int) {
	return file_common_types_jobs_proto_rawDescGZIP(), []int{0}
}

type RunJobResponse struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Status JobStatus              `protobuf:"varint,1,opt,name=status,proto3,enum=kiapi.common.types.JobStatus" json:"status,omitempty"`
	// The path of the generated output (may not actually exist in the filesystem if the job failed)
	// May be a file, multiple files, or a directory depending on the context of the job
	OutputPath []string `protobuf:"bytes,2,rep,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	// Optional message containing warning or error details. Should be empty if status is JS_SUCCESS.
	Message       string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobResponse) Reset() {
	*x = RunJobResponse{}
	mi := &file_common_types_jobs_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobResponse) ProtoMessage() {}

func (x *RunJobResponse) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_jobs_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobResponse.ProtoReflect.Descriptor instead.
func (*RunJobResponse) Descriptor() ([]byte, []int) {
	return file_common_types_jobs_proto_rawDescGZIP(), []int{0}
}

func (x *RunJobResponse) GetStatus() JobStatus {
	if x != nil {
		return x.Status
	}
	return JobStatus_JS_UNSPECIFIED
}

func (x *RunJobResponse) GetOutputPath() []string {
	if x != nil {
		return x.OutputPath
	}
	return nil
}

func (x *RunJobResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type RunJobSettings struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The document on which the job should be run
	Document *base_types.DocumentSpecifier `protobuf:"bytes,1,opt,name=document,proto3" json:"document,omitempty"`
	// The path where the job's output should be saved
	// May be a file or a directory depending on the context of the job
	OutputPath    string `protobuf:"bytes,2,opt,name=output_path,json=outputPath,proto3" json:"output_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RunJobSettings) Reset() {
	*x = RunJobSettings{}
	mi := &file_common_types_jobs_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RunJobSettings) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RunJobSettings) ProtoMessage() {}

func (x *RunJobSettings) ProtoReflect() protoreflect.Message {
	mi := &file_common_types_jobs_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RunJobSettings.ProtoReflect.Descriptor instead.
func (*RunJobSettings) Descriptor() ([]byte, []int) {
	return file_common_types_jobs_proto_rawDescGZIP(), []int{1}
}

func (x *RunJobSettings) GetDocument() *base_types.DocumentSpecifier {
	if x != nil {
		return x.Document
	}
	return nil
}

func (x *RunJobSettings) GetOutputPath() string {
	if x != nil {
		return x.OutputPath
	}
	return ""
}

var File_common_types_jobs_proto protoreflect.FileDescriptor

const file_common_types_jobs_proto_rawDesc = "" +
	"\n" +
	"\x17common/types/jobs.proto\x12\x12kiapi.common.types\x1a\x1dcommon/types/base_types.proto\"\x82\x01\n" +
	"\x0eRunJobResponse\x125\n" +
	"\x06status\x18\x01 \x01(\x0e2\x1d.kiapi.common.types.JobStatusR\x06status\x12\x1f\n" +
	"\voutput_path\x18\x02 \x03(\tR\n" +
	"outputPath\x12\x18\n" +
	"\amessage\x18\x03 \x01(\tR\amessage\"t\n" +
	"\x0eRunJobSettings\x12A\n" +
	"\bdocument\x18\x01 \x01(\v2%.kiapi.common.types.DocumentSpecifierR\bdocument\x12\x1f\n" +
	"\voutput_path\x18\x02 \x01(\tR\n" +
	"outputPath*M\n" +
	"\tJobStatus\x12\x12\n" +
	"\x0eJS_UNSPECIFIED\x10\x00\x12\x0e\n" +
	"\n" +
	"JS_SUCCESS\x10\x01\x12\x0e\n" +
	"\n" +
	"JS_WARNING\x10\x02\x12\f\n" +
	"\bJS_ERROR\x10\x03b\x06proto3"

var (
	file_common_types_jobs_proto_rawDescOnce sync.Once
	file_common_types_jobs_proto_rawDescData []byte
)

func file_common_types_jobs_proto_rawDescGZIP() []byte {
	file_common_types_jobs_proto_rawDescOnce.Do(func() {
		file_common_types_jobs_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_common_types_jobs_proto_rawDesc), len(file_common_types_jobs_proto_rawDesc)))
	})
	return file_common_types_jobs_proto_rawDescData
}

var file_common_types_jobs_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_common_types_jobs_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_common_types_jobs_proto_goTypes = []any{
	(JobStatus)(0),                       // 0: kiapi.common.types.JobStatus
	(*RunJobResponse)(nil),               // 1: kiapi.common.types.RunJobResponse
	(*RunJobSettings)(nil),               // 2: kiapi.common.types.RunJobSettings
	(*base_types.DocumentSpecifier)(nil), // 3: kiapi.common.types.DocumentSpecifier
}
var file_common_types_jobs_proto_depIdxs = []int32{
	0, // 0: kiapi.common.types.RunJobResponse.status:type_name -> kiapi.common.types.JobStatus
	3, // 1: kiapi.common.types.RunJobSettings.document:type_name -> kiapi.common.types.DocumentSpecifier
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_common_types_jobs_proto_init() }
func file_common_types_jobs_proto_init() {
	if File_common_types_jobs_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_common_types_jobs_proto_rawDesc), len(file_common_types_jobs_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_common_types_jobs_proto_goTypes,
		DependencyIndexes: file_common_types_jobs_proto_depIdxs,
		EnumInfos:         file_common_types_jobs_proto_enumTypes,
		MessageInfos:      file_common_types_jobs_proto_msgTypes,
	}.Build()
	File_common_types_jobs_proto = out.File
	file_common_types_jobs_proto_goTypes = nil
	file_common_types_jobs_proto_depIdxs = nil
}
