//! Generator for `docs/language-forms.md` — the machine-checked reference
//! for the S-expression design language. Every section is rendered from a
//! table the implementation itself dispatches on, so the docs cannot
//! drift from the evaluator:
//!
//!   - `src/eval/forms.zig`          special forms, builtin operators,
//!                                   design-scope forms (+ arity schema)
//!   - `src/eval/fmt.zig`            `(fmt …)` directive table
//!   - `src/sexpr/tokenizer.zig`     SI numeric-literal suffix tables
//!   - `src/render_block_types.zig`  section-name classifier keywords
//!
//! Three enforcement layers keep it honest: `requireAllDocumented` in
//! forms.zig turns an undocumented form into a compile error; per-table
//! sync tests (e.g. fmt's directive-dispatch test) prove each table
//! matches its dispatch; and `zig build test` runs
//! `gen-language-docs --check` plus the drift test below, so a stale
//! committed file fails the build. Regenerate with `zig build docs`.

const std = @import("std");
const forms = @import("eval/forms.zig");
const fmt_mod = @import("eval/fmt.zig");
const tokenizer_mod = @import("sexpr/tokenizer.zig");
const block_types = @import("render_block_types.zig");
const numeric = @import("numeric.zig");

/// Render the full Markdown reference. The output is deterministic — the
/// build's docs-check step and the drift test below compare it to the
/// checked-in `docs/language-forms.md`. Caller owns the returned slice.
pub fn renderLanguageReference(allocator: std.mem.Allocator) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    errdefer buf.deinit(allocator);
    try renderTo(buf.writer(allocator));
    return buf.toOwnedSlice(allocator);
}

fn renderTo(writer: anytype) !void {
    try writer.writeAll(
        \\# S-Expression Language: Form Reference
        \\
        \\<!-- Auto-generated by src/docgen.zig from the evaluator's own
        \\     dispatch tables. Do not edit by hand — run `zig build docs`
        \\     to regenerate; `zig build test` fails when this file is stale. -->
        \\
        \\Every special form, builtin operator, fmt directive, numeric-literal
        \\suffix, and design-scope form the toolchain recognises, with arity
        \\contracts and one-line summaries. The hand-written prose lives in
        \\[`sexp-language.md`](sexp-language.md); this file is the
        \\machine-checked grammar surface.
        \\
        \\## Special forms
        \\
        \\Arguments are passed un-evaluated; each form decides what to evaluate.
        \\
        \\| Form | Arity | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (forms.special_form_docs, 0..) |doc, i| {
        const variant: forms.SpecialForm = @enumFromInt(i);
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        try writeArity(writer, forms.schemaFor(variant));
        try writer.writeAll(" | ");
        try writeCell(writer, doc.summary);
        try writer.writeAll(" |\n");
    }

    try writer.writeAll(
        \\
        \\## Builtin operators
        \\
        \\Arithmetic, comparison, and logic operators. Arguments are evaluated left-to-right before the operator runs.
        \\
        \\| Form | Summary |
        \\| --- | --- |
        \\
    );
    for (forms.builtin_docs) |doc| {
        try writer.writeAll("| `");
        try writeCell(writer, doc.syntax);
        try writer.writeAll("` | ");
        try writeCell(writer, doc.summary);
        try writer.writeAll(" |\n");
    }

    try writer.writeAll(
        \\
        \\## String formatting directives
        \\
        \\Specifiers accepted in a `(fmt "template" args…)` template. Each
        \\consumes the next argument of the listed type (or none).
        \\
        \\| Directive | Argument | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (fmt_mod.directives) |d| {
        try writer.print("| `~{c}` | {s} | {s} |\n", .{
            d.spec,
            switch (d.arg) {
                .number => "number",
                .string => "string",
                .none => "—",
            },
            d.summary,
        });
    }

    try writer.writeAll(
        \\
        \\## Numeric literals
        \\
        \\Bare numbers accept an SI scale suffix, optionally followed by one
        \\unit letter that carries no scale (`100nF` == `100n`); a unit
        \\letter may also stand alone (`3.3V` == `3.3`). The suffix must end
        \\the token — `100kHz` falls through to a plain atom. Dimension
        \\tokens are separate: `mm` keeps the value in millimetres and `mil`
        \\converts to mm (1 mil = 0.0254 mm).
        \\
        \\| Suffix | Scale | Notes |
        \\| --- | --- | --- |
        \\
    );
    for (tokenizer_mod.si_scales) |s| {
        try writer.print("| `{c}` | 10^{d} | {s} |\n", .{
            s.letter,
            multiplierExponent(s.multiplier),
            if (s.bare) "" else "Only with a unit letter (`100mV`) — bare `3m`, `mm`, `mil` keep their dimension meanings.",
        });
    }
    try writer.writeAll("\nUnit letters (scale-free): ");
    for (tokenizer_mod.si_unit_letters, 0..) |u, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{c}`", .{u});
    }
    try writer.writeAll(".\n");

    try writer.writeAll(
        \\
        \\## Design-scope forms
        \\
        \\Forms that may appear directly inside a `(design-block …)`, a
        \\`(section …)`, or a nested sub-section. The scope column lists
        \\where each is accepted: **D** = design-block top level,
        \\**S** = section, **s** = sub-section.
        \\
        \\| Form | Scope | Summary |
        \\| --- | --- | --- |
        \\
    );
    for (forms.scope_form_docs) |row| {
        try writer.writeAll("| `");
        try writeCell(writer, row.doc.syntax);
        try writer.writeAll("` | ");
        if (row.scope.design_block) try writer.writeAll("D") else try writer.writeAll("·");
        if (row.scope.section) try writer.writeAll("S") else try writer.writeAll("·");
        if (row.scope.sub_section) try writer.writeAll("s") else try writer.writeAll("·");
        try writer.writeAll(" | ");
        try writeCell(writer, row.doc.summary);
        try writer.writeAll(" |\n");
    }

    try writer.writeAll(
        \\
        \\## Section-name classifier keywords
        \\
        \\The system-overview SVG picks each section's column + colour by
        \\case-insensitive keyword match on the section **name**, walking
        \\these rules in priority order (first hit wins). A section matching
        \\no rule falls back to **connector** when it contains a J/P-prefixed
        \\instance, else **peripheral**. An explicit `(category <key>)`
        \\declaration overrides the heuristic.
        \\
        \\| Category | Name keywords |
        \\| --- | --- |
        \\
    );
    for (block_types.name_rules) |rule| {
        try writer.print("| {s} | ", .{@tagName(rule.category)});
        for (rule.keywords, 0..) |kw, i| {
            if (i > 0) try writer.writeAll(", ");
            try writer.print("`{s}`", .{kw});
        }
        try writer.writeAll(" |\n");
    }
    try writer.writeAll("\nValid `(category <key>)` keys: ");
    for (std.enums.values(block_types.Category), 0..) |cat, i| {
        if (i > 0) try writer.writeAll(", ");
        try writer.print("`{s}`", .{@tagName(cat)});
    }
    try writer.writeAll(".\n");
}

/// Slice one `## `-headed section out of a rendered reference (heading
/// line through the byte before the next `## ` heading, or EOF). Matching
/// is case-insensitive on the heading title so MCP callers can ask for
/// "numeric literals". Returns null when no heading matches — derive the
/// valid titles with `SectionIterator`, never from a hardcoded list.
pub fn extractSection(doc: []const u8, title: []const u8) ?[]const u8 {
    var it = SectionIterator{ .doc = doc };
    while (it.next()) |sec| {
        if (std.ascii.eqlIgnoreCase(sec.title, title)) return sec.body;
    }
    return null;
}

/// One `## ` section of a rendered reference: the bare heading title and
/// the full body slice (heading line included).
pub const Section = struct { title: []const u8, body: []const u8 };

/// Walk the `## ` headings of a rendered reference in order. Keeps the
/// section list derived from the generated output itself, so a new doc
/// section is automatically addressable with zero registration.
pub const SectionIterator = struct {
    doc: []const u8,
    pos: usize = 0,

    pub fn next(self: *SectionIterator) ?Section {
        const start = findHeading(self.doc, self.pos) orelse return null;
        const title_start = start + "## ".len;
        const title_end = std.mem.indexOfScalarPos(u8, self.doc, title_start, '\n') orelse self.doc.len;
        const end = findHeading(self.doc, title_end) orelse self.doc.len;
        self.pos = end;
        return .{
            .title = std.mem.trim(u8, self.doc[title_start..title_end], " \r"),
            .body = self.doc[start..end],
        };
    }

    /// Byte offset of the next line starting with `## `, at or after `from`.
    fn findHeading(doc: []const u8, from: usize) ?usize {
        var i = from;
        while (std.mem.indexOfPos(u8, doc, i, "## ")) |hit| {
            if (hit == 0 or doc[hit - 1] == '\n') return hit;
            i = hit + 1;
        }
        return null;
    }
};

/// Write table-cell content, escaping `|` so syntax templates like
/// `(status concept|implemented|review)` don't split the Markdown cell.
fn writeCell(writer: anytype, text: []const u8) !void {
    for (text) |c| {
        if (c == '|') try writer.writeAll("\\|") else try writer.writeByte(c);
    }
}

fn writeArity(writer: anytype, schema: ?forms.FormSchema) !void {
    const s = schema orelse {
        try writer.writeAll("—");
        return;
    };
    if (s.max_args) |max| {
        if (max == s.min_args) {
            try writer.print("{d}", .{s.min_args});
        } else {
            try writer.print("{d}–{d}", .{ s.min_args, max });
        }
    } else {
        try writer.print("{d}+", .{s.min_args});
    }
}

/// Power-of-ten exponent of an SI multiplier (all entries in
/// `tokenizer.si_scales` are exact powers of ten).
fn multiplierExponent(m: f64) i32 {
    return numeric.checkedInt(i32, @round(@log10(m))) orelse 0;
}

// ── Tests ──────────────────────────────────────────────────────────────

// spec: docgen - renderLanguageReference output matches the committed docs/language-forms.md so docs can never lag the registries
test "language-forms.md is in sync with the dispatch tables" {
    const alloc = std.testing.allocator;

    // Skip when the test is invoked outside a project tree (the file
    // simply isn't there to compare against) — the build's
    // `gen-language-docs --check` step still enforces presence + sync
    // with a deterministic cwd.
    var file = std.fs.cwd().openFile("docs/language-forms.md", .{}) catch return;
    defer file.close();
    const committed = try file.readToEndAlloc(alloc, 1024 * 1024);
    defer alloc.free(committed);

    const generated = try renderLanguageReference(alloc);
    defer alloc.free(generated);

    // expectEqualStrings produces a usable diff on failure. To
    // regenerate the file, run `zig build docs`.
    try std.testing.expectEqualStrings(committed, generated);
}

// spec: docgen - extractSection returns one ## section of the rendered reference, matching the title case-insensitively
test "extractSection slices one heading's section" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    const sec = extractSection(doc, "numeric literals").?;
    try std.testing.expect(std.mem.startsWith(u8, sec, "## Numeric literals"));
    try std.testing.expect(std.mem.indexOf(u8, sec, "## Design-scope forms") == null);
    try std.testing.expect(extractSection(doc, "no such section") == null);
}

/// (helper) Count the `## ` sections an iterator yields.
fn countSections(doc: []const u8) usize {
    var it = SectionIterator{ .doc = doc };
    var n: usize = 0;
    while (it.next()) |_| n += 1;
    return n;
}

// spec: docgen - SectionIterator walks every ## heading of the rendered reference in order
test "SectionIterator finds the reference sections" {
    const alloc = std.testing.allocator;
    const doc = try renderLanguageReference(alloc);
    defer alloc.free(doc);

    var it = SectionIterator{ .doc = doc };
    const first = it.next().?;
    try std.testing.expectEqualStrings("Special forms", first.title);
    try std.testing.expect(countSections(doc) >= 6);
}

// spec: docgen - The generated reference names every category key so (category …) docs follow the classifier map
test "category keys section covers the classifier map" {
    // Every key in the classifier's `(category <key>)` map must be a
    // Category enum tag name — the doc section walks the enum, so an
    // alias key added only to the map would silently go undocumented.
    for (block_types.category_keys.keys()) |key| {
        try std.testing.expect(std.meta.stringToEnum(block_types.Category, key) != null);
    }
}
