const std = @import("std");
const parser_mod = @import("sexpr/parser.zig");
const ast = @import("sexpr/ast.zig");
const Node = ast.Node;

/// PCB layout data: component placements, traces, vias, and zone fills.
/// Parsed from and written to `.layout` files (s-expression format).
pub const Rules = struct {
    clearance: f64 = 0.15,
    track_width: f64 = 0.2,
    via_drill: f64 = 0.3,
    via_size: f64 = 0.6,
};

pub const Layout = struct {
    placements: []const Placement,
    traces: []const Trace,
    vias: []const Via,
    zone_fills: []const ZoneFill,
    rules: ?Rules = null,
};

pub const Side = enum { front, back };

pub const Placement = struct {
    ref_des: []const u8,
    x: f64,
    y: f64,
    angle: f64,
    side: Side,
    uuid: []const u8,
};

pub const Trace = struct {
    net: []const u8,
    layer: []const u8,
    width: f64,
    points: []const [2]f64,
};

pub const Via = struct {
    x: f64,
    y: f64,
    net: []const u8,
    drill: f64,
    pad_size: f64,
    layer_from: []const u8,
    layer_to: []const u8,
};

pub const ZoneFill = struct {
    zone_name: []const u8,
    layer: []const u8,
    polygons: []const []const [2]f64,
};

/// Load a layout from a `.layout` file.
pub fn loadLayout(allocator: std.mem.Allocator, path: []const u8) !Layout {
    const source = try std.fs.cwd().readFileAlloc(allocator, path, 10 * 1024 * 1024);
    const nodes = try parser_mod.parse(allocator, source);

    var placements: std.ArrayListUnmanaged(Placement) = .empty;
    var traces: std.ArrayListUnmanaged(Trace) = .empty;
    var vias: std.ArrayListUnmanaged(Via) = .empty;
    var zone_fills: std.ArrayListUnmanaged(ZoneFill) = .empty;
    var rules: ?Rules = null;

    for (nodes) |node| {
        const children = node.asList() orelse continue;
        if (children.len == 0) continue;
        const tag = children[0].asAtom() orelse continue;

        if (std.mem.eql(u8, tag, "place")) {
            const p = parsePlacement(children) orelse continue;
            try placements.append(allocator, p);
        } else if (std.mem.eql(u8, tag, "trace")) {
            const t = parseTrace(allocator, children) orelse continue;
            try traces.append(allocator, t);
        } else if (std.mem.eql(u8, tag, "via")) {
            const v = parseVia(children) orelse continue;
            try vias.append(allocator, v);
        } else if (std.mem.eql(u8, tag, "zone-fill")) {
            const z = parseZoneFill(allocator, children) orelse continue;
            try zone_fills.append(allocator, z);
        } else if (std.mem.eql(u8, tag, "rules")) {
            rules = parseRules(children);
        }
    }

    return .{
        .placements = try placements.toOwnedSlice(allocator),
        .traces = try traces.toOwnedSlice(allocator),
        .vias = try vias.toOwnedSlice(allocator),
        .zone_fills = try zone_fills.toOwnedSlice(allocator),
        .rules = rules,
    };
}

/// Save a layout to a `.layout` file.
pub fn saveLayout(allocator: std.mem.Allocator, layout: *const Layout, path: []const u8) !void {
    var buf: std.ArrayListUnmanaged(u8) = .empty;
    defer buf.deinit(allocator);
    const w = buf.writer(allocator);

    try w.writeAll(";; Layout — auto-generated by eda\n;; Do not edit by hand\n\n");

    // Placements
    for (layout.placements) |p| {
        try w.print("(place \"{s}\" {d:.2} {d:.2} {d:.0} {s} \"{s}\")\n", .{
            p.ref_des,
            p.x,
            p.y,
            p.angle,
            @tagName(p.side),
            p.uuid,
        });
    }

    // Traces
    if (layout.traces.len > 0) {
        try w.writeAll("\n");
        for (layout.traces) |t| {
            try w.print("(trace \"{s}\" \"{s}\" {d:.2}\n ", .{ t.net, t.layer, t.width });
            for (t.points, 0..) |pt, i| {
                if (i > 0) try w.writeAll("  ");
                try w.print("{d:.2} {d:.2}", .{ pt[0], pt[1] });
            }
            try w.writeAll(")\n");
        }
    }

    // Vias
    if (layout.vias.len > 0) {
        try w.writeAll("\n");
        for (layout.vias) |v| {
            try w.print("(via {d:.2} {d:.2} \"{s}\" {d:.2} {d:.2} \"{s}\" \"{s}\")\n", .{
                v.x, v.y, v.net, v.drill, v.pad_size, v.layer_from, v.layer_to,
            });
        }
    }

    // Zone fills
    if (layout.zone_fills.len > 0) {
        try w.writeAll("\n");
        for (layout.zone_fills) |z| {
            try w.print("(zone-fill \"{s}\" \"{s}\"\n", .{ z.zone_name, z.layer });
            for (z.polygons) |poly| {
                try w.writeAll("  (polygon");
                for (poly) |pt| {
                    try w.print(" {d:.2} {d:.2}", .{ pt[0], pt[1] });
                }
                try w.writeAll(")\n");
            }
            try w.writeAll(")\n");
        }
    }

    // Rules
    if (layout.rules) |r| {
        try w.print("\n(rules {d:.2} {d:.2} {d:.2} {d:.2})\n", .{ r.clearance, r.track_width, r.via_drill, r.via_size });
    }

    // Write to file
    if (std.fs.path.dirname(path)) |dir| {
        try std.fs.cwd().makePath(dir);
    }
    const file = try std.fs.cwd().createFile(path, .{});
    defer file.close();
    try file.writeAll(buf.items);
}

/// Build a uuid→Placement map from a Layout for quick lookup.
pub fn placementsByUuid(allocator: std.mem.Allocator, layout: *const Layout) !std.StringHashMap(Placement) {
    var map = std.StringHashMap(Placement).init(allocator);
    for (layout.placements) |p| {
        try map.put(p.uuid, p);
    }
    return map;
}

// --- Parsers for individual forms ---

/// (place "ref" x y angle side "uuid")
fn parsePlacement(children: []const Node) ?Placement {
    if (children.len < 7) return null;
    return .{
        .ref_des = children[1].asString() orelse return null,
        .x = nodeFloat(children[2]) orelse return null,
        .y = nodeFloat(children[3]) orelse return null,
        .angle = nodeFloat(children[4]) orelse 0,
        .side = blk: {
            const s = children[5].asAtom() orelse return null;
            break :blk if (std.mem.eql(u8, s, "back")) .back else .front;
        },
        .uuid = children[6].asString() orelse return null,
    };
}

/// (trace "net" "layer" width x1 y1 x2 y2 ...)
fn parseTrace(allocator: std.mem.Allocator, children: []const Node) ?Trace {
    if (children.len < 6) return null;
    const net = children[1].asString() orelse return null;
    const layer = children[2].asString() orelse return null;
    const width = nodeFloat(children[3]) orelse return null;

    // Remaining children are x,y coordinate pairs
    var points: std.ArrayListUnmanaged([2]f64) = .empty;
    var i: usize = 4;
    while (i + 1 < children.len) : (i += 2) {
        const x = nodeFloat(children[i]) orelse break;
        const y = nodeFloat(children[i + 1]) orelse break;
        points.append(allocator, .{ x, y }) catch return null;
    }
    if (points.items.len < 2) return null;

    return .{
        .net = net,
        .layer = layer,
        .width = width,
        .points = points.toOwnedSlice(allocator) catch return null,
    };
}

/// (via x y "net" drill pad_size "from" "to")
fn parseVia(children: []const Node) ?Via {
    if (children.len < 8) return null;
    return .{
        .x = nodeFloat(children[1]) orelse return null,
        .y = nodeFloat(children[2]) orelse return null,
        .net = children[3].asString() orelse return null,
        .drill = nodeFloat(children[4]) orelse return null,
        .pad_size = nodeFloat(children[5]) orelse return null,
        .layer_from = children[6].asString() orelse return null,
        .layer_to = children[7].asString() orelse return null,
    };
}

/// (zone-fill "name" "layer" (polygon x1 y1 x2 y2 ...) ...)
fn parseZoneFill(allocator: std.mem.Allocator, children: []const Node) ?ZoneFill {
    if (children.len < 3) return null;
    const zone_name = children[1].asString() orelse return null;
    const layer = children[2].asString() orelse return null;

    var polygons: std.ArrayListUnmanaged([]const [2]f64) = .empty;
    for (children[3..]) |child| {
        const sub = child.asList() orelse continue;
        if (sub.len < 3) continue;
        const stag = sub[0].asAtom() orelse continue;
        if (!std.mem.eql(u8, stag, "polygon")) continue;

        var pts: std.ArrayListUnmanaged([2]f64) = .empty;
        var i: usize = 1;
        while (i + 1 < sub.len) : (i += 2) {
            const x = nodeFloat(sub[i]) orelse break;
            const y = nodeFloat(sub[i + 1]) orelse break;
            pts.append(allocator, .{ x, y }) catch return null;
        }
        if (pts.items.len >= 3) {
            polygons.append(allocator, pts.toOwnedSlice(allocator) catch return null) catch return null;
        }
    }

    return .{
        .zone_name = zone_name,
        .layer = layer,
        .polygons = polygons.toOwnedSlice(allocator) catch return null,
    };
}

// (rules clearance track_width via_drill via_size)
fn parseRules(children: []const Node) ?Rules {
    if (children.len < 5) return null;
    return .{
        .clearance = nodeFloat(children[1]) orelse return null,
        .track_width = nodeFloat(children[2]) orelse return null,
        .via_drill = nodeFloat(children[3]) orelse return null,
        .via_size = nodeFloat(children[4]) orelse return null,
    };
}

fn nodeFloat(node: anytype) ?f64 {
    if (node.asNumber()) |n| return n;
    if (node.asAtom()) |s| return std.fmt.parseFloat(f64, s) catch null;
    return null;
}

// --- Tests ---

const testing = std.testing;

// spec: layout - Parses placement from layout source
test "parse placement" {
    const alloc = testing.allocator;
    const source =
        \\(place "U3" 30.50 20.10 0 front "2bc6897c-52c9-5e1e-a6c3-e01f6ff60d14")
        \\(place "C1" 10.00 15.00 90 back "d04a86d5-7e1d-5b3c-a3d2-392d0c0af5e9")
    ;
    const nodes = try parser_mod.parse(alloc, source);
    defer alloc.free(nodes);

    const p1 = parsePlacement(nodes[0].asList().?).?;
    try testing.expectEqualStrings("U3", p1.ref_des);
    try testing.expectApproxEqAbs(30.5, p1.x, 0.01);
    try testing.expectApproxEqAbs(20.1, p1.y, 0.01);
    try testing.expectEqual(Side.front, p1.side);

    const p2 = parsePlacement(nodes[1].asList().?).?;
    try testing.expectEqualStrings("C1", p2.ref_des);
    try testing.expectEqual(@as(f64, 90), p2.angle);
    try testing.expectEqual(Side.back, p2.side);
}

// spec: layout - Parses trace from layout source
test "parse trace" {
    const alloc = testing.allocator;
    const source =
        \\(trace "GND" "F.Cu" 0.2 10.0 15.0 20.0 15.0 20.0 25.0)
    ;
    const nodes = try parser_mod.parse(alloc, source);
    defer alloc.free(nodes);

    const t = parseTrace(alloc, nodes[0].asList().?).?;
    defer alloc.free(t.points);
    try testing.expectEqualStrings("GND", t.net);
    try testing.expectEqualStrings("F.Cu", t.layer);
    try testing.expectApproxEqAbs(0.2, t.width, 0.01);
    try testing.expectEqual(@as(usize, 3), t.points.len);
    try testing.expectApproxEqAbs(20.0, t.points[2][0], 0.01);
    try testing.expectApproxEqAbs(25.0, t.points[2][1], 0.01);
}
