const std = @import("std");
const httpz = @import("httpz");

const server_mod = @import("../serve.zig");
const Handler = server_mod.Handler;
const auth = @import("auth.zig");
const store = @import("oauth_store.zig");
const users = @import("users.zig");
const account_template = @import("templates/account.zig");

// ── Constants ─────────────────────────────────────────────────────
const err_expected_object = "expected object";
const err_invalid_json = "invalid json";
const err_missing_body = "missing body";
const ok_json_true = "{\"ok\":true}";

/// Error set for HTTP handlers in this module. Wide enough to absorb
/// the file-IO and form-parsing errors propagated by every helper called
/// from the bodies via `try`.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error ||
    std.fs.File.WriteError || std.fs.File.OpenError || std.fs.File.ReadError ||
    std.fs.Dir.MakeError || std.fs.Dir.StatFileError ||
    error{ LastAdmin, CannotDeleteSelf, FileTooBig, StreamTooLong, EndOfStream, InvalidEscapeSequence };

fn currentEmail(ctx: *Handler, req: *httpz.Request) ?[]const u8 {
    return auth.currentEmail(ctx, req);
}

/// GET /account
/// Unified account page: passkeys, invite link, and OAuth clients for MCP.
/// Markup is generated by the `zt` template at `templates/account.zt`.
pub fn accountPage(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const email = currentEmail(ctx, req) orelse {
        res.status = 303;
        res.header("location", "/auth/login");
        return;
    };

    const clients = try store.listClientsByEmail(ctx.allocator, ctx.auth_dir, email);
    defer ctx.allocator.free(clients);

    const current_role = users.getRole(ctx.allocator, ctx.auth_dir, email);
    const is_admin = current_role.canAdmin();

    const user_list: []users.User = if (is_admin)
        try users.listUsers(ctx.allocator, ctx.auth_dir)
    else
        &[_]users.User{};
    defer if (is_admin) ctx.allocator.free(user_list);

    var aw: std.Io.Writer.Allocating = .init(req.arena);
    try account_template.Account.render(
        .{ email, current_role, is_admin, user_list, clients },
        &aw.writer,
    );
    res.content_type = .HTML;
    res.body = aw.written();
}

/// POST /api/oauth/clients
/// Body: {"name":"...","redirect_uri":"..."}
pub fn createClientApi(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const email = currentEmail(ctx, req) orelse {
        res.status = 401;
        res.body = "sign in required";
        return;
    };
    const body = req.body() orelse {
        res.status = 400;
        res.body = err_missing_body;
        return;
    };

    const parsed = std.json.parseFromSlice(std.json.Value, req.arena, body, .{}) catch {
        res.status = 400;
        res.body = err_invalid_json;
        return;
    };
    if (parsed.value != .object) {
        res.status = 400;
        res.body = err_expected_object;
        return;
    }
    const name = if (parsed.value.object.get("name")) |v| (if (v == .string) v.string else "") else "";
    const redirect_uri = if (parsed.value.object.get("redirect_uri")) |v| (if (v == .string) v.string else "") else "";
    if (name.len == 0 or redirect_uri.len == 0) {
        res.status = 400;
        res.body = "name and redirect_uri are required";
        return;
    }

    const r = try store.createClient(ctx.allocator, ctx.auth_dir, name, email, redirect_uri);
    res.content_type = .JSON;
    res.body = try std.fmt.allocPrint(
        req.arena,
        \\{{"client_id":"{s}","client_secret":"{s}"}}
    ,
        .{ r.id, r.secret },
    );
}

/// POST /api/oauth/clients/:id/revoke
pub fn revokeClientApi(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const email = currentEmail(ctx, req) orelse {
        res.status = 401;
        res.body = "sign in required";
        return;
    };
    const id = req.param("id") orelse {
        res.status = 400;
        res.body = "missing id";
        return;
    };
    const ok = store.revokeClient(ctx.allocator, ctx.auth_dir, id, email);
    if (!ok) {
        res.status = 404;
        res.body = "client not found";
        return;
    }
    res.content_type = .JSON;
    res.body = ok_json_true;
}

/// GET /auth/manage — legacy redirect to /account.
pub fn manageRedirect(_: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    res.status = 303;
    res.header("location", "/account");
}

fn requireAdmin(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) ?[]const u8 {
    const email = currentEmail(ctx, req) orelse {
        res.status = 401;
        res.content_type = .JSON;
        res.body = "{\"error\":\"sign in required\"}";
        return null;
    };
    if (!users.getRole(ctx.allocator, ctx.auth_dir, email).canAdmin()) {
        res.status = 403;
        res.content_type = .JSON;
        res.body = "{\"error\":\"admin role required\"}";
        return null;
    }
    return email;
}

/// POST /api/users/role
/// Body: {"email":"target@example.com","role":"admin"|"writer"|"reader"}
pub fn updateUserRoleApi(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const actor = requireAdmin(ctx, req, res) orelse return;
    const body = req.body() orelse {
        res.status = 400;
        res.body = err_missing_body;
        return;
    };
    const parsed = std.json.parseFromSlice(std.json.Value, req.arena, body, .{}) catch {
        res.status = 400;
        res.body = err_invalid_json;
        return;
    };
    if (parsed.value != .object) {
        res.status = 400;
        res.body = err_expected_object;
        return;
    }
    const target = if (parsed.value.object.get("email")) |v| (if (v == .string) v.string else "") else "";
    if (target.len == 0) {
        res.status = 400;
        res.body = "missing email";
        return;
    }
    const role_raw = if (parsed.value.object.get("role")) |v| (if (v == .string) v.string else "") else "";
    const new_role = users.Role.fromString(role_raw) orelse {
        res.status = 400;
        res.body = "unknown role";
        return;
    };

    const ok = users.setRole(ctx.allocator, ctx.auth_dir, target, new_role, actor) catch |err| {
        if (err == error.LastAdmin) {
            res.status = 409;
            res.content_type = .JSON;
            res.body = "{\"error\":\"cannot demote the last admin\"}";
            return;
        }
        return err;
    };
    if (!ok) {
        res.status = 404;
        res.body = "user not found";
        return;
    }
    res.content_type = .JSON;
    res.body = ok_json_true;
}

/// POST /api/users/delete
/// Body: {"email":"target@example.com"}
/// Removes the user record, revokes all their OAuth clients, deletes their
/// passkeys, and drops their sessions. Admin-only. Cannot delete yourself or
/// the last admin.
pub fn deleteUserApi(ctx: *Handler, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const actor = requireAdmin(ctx, req, res) orelse return;
    const body = req.body() orelse {
        res.status = 400;
        res.body = err_missing_body;
        return;
    };
    const parsed = std.json.parseFromSlice(std.json.Value, req.arena, body, .{}) catch {
        res.status = 400;
        res.body = err_invalid_json;
        return;
    };
    if (parsed.value != .object) {
        res.status = 400;
        res.body = err_expected_object;
        return;
    }
    const target = if (parsed.value.object.get("email")) |v| (if (v == .string) v.string else "") else "";
    if (target.len == 0) {
        res.status = 400;
        res.body = "missing email";
        return;
    }

    const ok = users.deleteUser(ctx.allocator, ctx.auth_dir, target, actor) catch |err| {
        res.status = 409;
        res.content_type = .JSON;
        res.body = switch (err) {
            error.CannotDeleteSelf => "{\"error\":\"you cannot delete your own account\"}",
            error.LastAdmin => "{\"error\":\"cannot delete the last admin\"}",
            else => return err,
        };
        return;
    };
    if (!ok) {
        res.status = 404;
        res.body = "user not found";
        return;
    }

    // Cascade: revoke OAuth clients, drop passkeys + sessions.
    store.revokeAllClientsForEmail(ctx.allocator, ctx.auth_dir, target);
    auth.purgeIdentity(ctx.allocator, ctx.auth_dir, target);

    res.content_type = .JSON;
    res.body = ok_json_true;
}
