const std = @import("std");
const httpz = @import("httpz");
const clock = @import("../infra/clock.zig");
const Evaluator = @import("../eval/evaluator.zig").Evaluator;
const env_mod = @import("../eval/env.zig");
const serve_root = @import("../serve.zig");
const Handler = serve_root.Handler;
const bom_html = @import("bom_html.zig");
const assets_css = @import("assets_css.zig");
const library = @import("library.zig");
const mcp_tools = @import("mcp_tools.zig");
const home_template = @import("templates/pages.zig");

/// Error set for HTTP handlers in this module: only writer-side errors
/// propagate back to httpz; everything else is caught internally and
/// translated to a 5xx body.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error;

/// GET / — render the home page: a card grid of every `.sexp` design under
/// `src/` with title, instance/net counts, recent-mtime badge, section
/// chips, and a link to the Schematic for each. The markup itself is
/// generated by the `zt` template at `templates/pages.zt`.
pub fn indexPage(ctx: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const summaries = mcp_tools.listDesignSummaries(ctx.allocator, ctx.project_dir) catch &[_]mcp_tools.DesignSummary{};
    const now_sec: i64 = @intCast(@divTrunc(clock.nanoTimestamp(), clock.ns_per_s));

    var aw: std.Io.Writer.Allocating = .init(ctx.allocator);
    try home_template.Home.render(.{ summaries, now_sec }, &aw.writer);
    res.body = aw.written();
    res.content_type = .HTML;
}

/// GET /style.css — serve the static stylesheet shared by the index page
/// and other plain-HTML pages so they pick up the dark theme without
/// inlining the CSS into every response.
pub fn cssPage(_: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    res.content_type = .CSS;
    res.body = assets_css.INDEX_CSS;
}
