const std = @import("std");
const httpz = @import("httpz");
const clock = @import("../infra/clock.zig");
const Evaluator = @import("../eval/evaluator.zig").Evaluator;
const env_mod = @import("../eval/env.zig");
const serve_root = @import("../serve.zig");
const Handler = serve_root.Handler;
const bom_html = @import("bom_html.zig");
const assets_css = @import("assets_css.zig");
const library = @import("library.zig");
const mcp_tools = @import("mcp_tools.zig");
const modules_page = @import("modules.zig");
const home_template = @import("templates/pages.zig");

/// Error set for HTTP handlers in this module: only writer-side errors
/// propagate back to httpz; everything else is caught internally and
/// translated to a 5xx body.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error;

/// GET / — render the home page: a card grid of every `.sexp` design under
/// `src/` (title, instance/net counts, recent-mtime badge, section chips)
/// followed by a card grid of every `lib/modules/` module with its
/// parameter list and the designs that instantiate it. The markup itself
/// is generated by the `zt` template at `templates/pages.zt`.
pub fn indexPage(ctx: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const summaries = mcp_tools.listDesignSummaries(ctx.allocator, ctx.project_dir) catch &[_]mcp_tools.DesignSummary{};
    const modules = collectHomeModules(ctx.allocator, ctx.project_dir, summaries) catch &[_]home_template.ModuleHomeEntry{};
    const now_sec: i64 = @intCast(@divTrunc(clock.nanoTimestamp(), clock.ns_per_s));

    var aw: std.Io.Writer.Allocating = .init(ctx.allocator);
    try home_template.Home.render(.{ summaries, modules, now_sec }, &aw.writer);
    res.body = aw.written();
    res.content_type = .HTML;
}

/// Join the lib/modules inventory with each design's `modules_used` list so
/// every module card can say which designs instantiate it.
fn collectHomeModules(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    summaries: []const mcp_tools.DesignSummary,
) ![]home_template.ModuleHomeEntry {
    const mods = try modules_page.collectModules(allocator, project_dir);
    var entries: std.ArrayListUnmanaged(home_template.ModuleHomeEntry) = .empty;
    for (mods) |m| {
        var used_by: std.ArrayListUnmanaged([]const u8) = .empty;
        for (summaries) |s| {
            for (s.modules_used) |u| {
                if (std.mem.eql(u8, u, m.name)) {
                    try used_by.append(allocator, s.name);
                    break;
                }
            }
        }
        try entries.append(allocator, .{
            .name = m.name,
            .params = m.params,
            .doc = m.doc,
            .used_by = try used_by.toOwnedSlice(allocator),
        });
    }
    return entries.toOwnedSlice(allocator);
}

/// GET /style.css — serve the static stylesheet shared by the index page
/// and other plain-HTML pages so they pick up the dark theme without
/// inlining the CSS into every response.
pub fn cssPage(_: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    res.content_type = .CSS;
    res.body = assets_css.INDEX_CSS;
}
