const std = @import("std");
const httpz = @import("httpz");
const clock = @import("../infra/clock.zig");
const Evaluator = @import("../eval/evaluator.zig").Evaluator;
const env_mod = @import("../eval/env.zig");
const serve_root = @import("../serve.zig");
const Handler = serve_root.Handler;
const bom_html = @import("bom_html.zig");
const assets_css = @import("assets_css.zig");
const library = @import("library.zig");
const mcp_tools = @import("mcp_tools.zig");
const modules_page = @import("modules.zig");
const home_template = @import("templates/pages.zig");
const layout_status = @import("../layout_status.zig");

/// Error set for HTTP handlers in this module: only writer-side errors
/// propagate back to httpz; everything else is caught internally and
/// translated to a 5xx body.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error;

/// GET / — render the home page: a card grid of every `.sexp` design under
/// `src/` (title, instance/net counts, recent-mtime badge, section chips)
/// followed by a card grid of every `lib/modules/` module with its
/// parameter list and the designs that instantiate it. The markup itself
/// is generated by the `zt` template at `templates/pages.zt`.
pub fn indexPage(ctx: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const summaries = mcp_tools.listDesignSummaries(ctx.allocator, ctx.project_dir) catch &[_]mcp_tools.DesignSummary{};
    const modules = collectHomeModules(ctx.allocator, ctx.project_dir, summaries) catch &[_]home_template.ModuleHomeEntry{};
    const now_sec: i64 = @intCast(@divTrunc(clock.nanoTimestamp(), clock.ns_per_s));

    const design_cards = buildDesignCards(ctx.allocator, ctx.project_dir, summaries) catch &[_]home_template.DesignCardVM{};
    const module_cards = buildModuleCards(ctx.allocator, modules) catch &[_]home_template.ModuleCardVM{};

    var aw: std.Io.Writer.Allocating = .init(ctx.allocator);
    try home_template.Home.render(.{ design_cards, module_cards, now_sec }, &aw.writer);
    res.body = aw.written();
    res.content_type = .HTML;
}

/// Pair every design summary with the search haystack the home page's
/// client-side filter AND-matches query terms against, plus its "starred"
/// flag. The starred flag is read fresh from the design's `.layouts.json`
/// sidecar (NOT from the read-set-cached summary) so starring a layout shows
/// up on the next home load.
fn buildDesignCards(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    summaries: []const mcp_tools.DesignSummary,
) ![]home_template.DesignCardVM {
    const out = try allocator.alloc(home_template.DesignCardVM, summaries.len);
    for (summaries, out) |s, *card| {
        const starred = layout_status.read(allocator, project_dir, s.name).starred;
        card.* = .{
            .s = s,
            .has_starred = starred,
            .search = try designSearchText(allocator, s, starred),
        };
    }
    return out;
}

/// Pair every module entry with its search haystack.
fn buildModuleCards(
    allocator: std.mem.Allocator,
    modules: []const home_template.ModuleHomeEntry,
) ![]home_template.ModuleCardVM {
    const out = try allocator.alloc(home_template.ModuleCardVM, modules.len);
    for (modules, out) |m, *card| {
        card.* = .{ .m = m, .search = try moduleSearchText(allocator, m) };
    }
    return out;
}

/// "<role> <name> <title> <section…>" — the searchable text for a design
/// card. The leading role tag word ("board" or "subcircuit") makes a query of
/// either word surface the matching cards (mirroring the visible type tag);
/// the "grouping"/"starred" tag words mirror the visible status tags so the
/// same words filter them.
fn designSearchText(
    allocator: std.mem.Allocator,
    s: mcp_tools.DesignSummary,
    starred: bool,
) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, if (s.is_board) "board " else "subcircuit ");
    try buf.appendSlice(allocator, s.name);
    if (s.title.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, s.title);
    }
    for (s.sections) |sec| {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, sec);
    }
    try appendTagWords(allocator, &buf, s.has_groups, starred);
    return buf.items;
}

/// Append the " grouping"/" starred" haystack words so a text query of either
/// tag word filters to the cards showing it. Shared by design + module cards.
fn appendTagWords(
    allocator: std.mem.Allocator,
    buf: *std.ArrayList(u8),
    has_groups: bool,
    starred: bool,
) std.mem.Allocator.Error!void {
    if (has_groups) try buf.appendSlice(allocator, " grouping");
    if (starred) try buf.appendSlice(allocator, " starred");
}

/// "subcircuit <name> <params> <doc>" — the searchable text for a module
/// card. Modules are reusable subcircuits, so the leading role tag word is
/// "subcircuit" (matching the visible type tag + the Subcircuits filter).
fn moduleSearchText(
    allocator: std.mem.Allocator,
    m: home_template.ModuleHomeEntry,
) std.mem.Allocator.Error![]const u8 {
    var buf: std.ArrayList(u8) = .empty;
    try buf.appendSlice(allocator, "subcircuit ");
    try buf.appendSlice(allocator, m.name);
    if (m.params.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, m.params);
    }
    if (m.doc.len > 0) {
        try buf.append(allocator, ' ');
        try buf.appendSlice(allocator, m.doc);
    }
    try appendTagWords(allocator, &buf, m.has_groups, m.has_starred);
    return buf.items;
}

/// Join the lib/modules inventory with each design's `modules_used` list so
/// every module card can say which designs instantiate it.
fn collectHomeModules(
    allocator: std.mem.Allocator,
    project_dir: []const u8,
    summaries: []const mcp_tools.DesignSummary,
) ![]home_template.ModuleHomeEntry {
    const mods = try modules_page.collectModules(allocator, project_dir);
    var entries: std.ArrayList(home_template.ModuleHomeEntry) = .empty;
    for (mods) |m| {
        var used_by: std.ArrayList([]const u8) = .empty;
        for (summaries) |s| {
            for (s.modules_used) |u| {
                if (std.mem.eql(u8, u, m.name)) {
                    try used_by.append(allocator, s.name);
                    break;
                }
            }
        }
        try entries.append(allocator, .{
            .name = m.name,
            .params = m.params,
            .doc = m.doc,
            .used_by = try used_by.toOwnedSlice(allocator),
            .has_groups = m.has_groups,
            // Read fresh each load so starring a module's layout shows up here.
            .has_starred = layout_status.read(allocator, project_dir, m.name).starred,
        });
    }
    return entries.toOwnedSlice(allocator);
}

/// GET /style.css — serve the static stylesheet shared by the index page
/// and other plain-HTML pages so they pick up the dark theme without
/// inlining the CSS into every response.
pub fn cssPage(_: *Handler, _: *httpz.Request, res: *httpz.Response) HandlerError!void {
    res.content_type = .CSS;
    res.body = assets_css.INDEX_CSS;
}
