const std = @import("std");
const httpz = @import("httpz");
const serve_root = @import("../serve.zig");
const Server = serve_root.Server;
const pdf_template = @import("templates/pdf_viewer.zig");

/// Error set for HTTP handlers in this module.
pub const HandlerError = std.mem.Allocator.Error || std.Io.Writer.Error;

/// GET /pdf-view/:filename — interactive datasheet viewer backed by PDF.js
/// loaded from jsDelivr. Query params: `page=N` (1-based; jump on load) and
/// `highlight=S` (substring to mark; first hit is scrolled into view). The
/// underlying PDF is fetched from the existing `/datasheets/:filename` route.
///
/// Markup is generated by `templates/pdf_viewer.zt`; the CSS + JS module are
/// served separately from `/static/pdf_viewer.{css,js}`.
pub fn pdfViewerPage(ctx: *Server, req: *httpz.Request, res: *httpz.Response) HandlerError!void {
    const filename = req.param("filename") orelse {
        res.status = 404;
        return;
    };
    if (filename.len == 0 or std.mem.indexOfAny(u8, filename, "/\\") != null or std.mem.indexOf(u8, filename, "..") != null) {
        res.status = 400;
        res.body = "invalid filename";
        return;
    }

    var aw: std.Io.Writer.Allocating = .init(ctx.allocator);
    try pdf_template.Page.render(.{filename}, &aw.writer);
    res.content_type = .HTML;
    res.body = aw.written();
}
